### PR TITLE
feat(button): implement opacity for disabled button

### LINKED ISSUE #16965: [Ionic v4] override the opacity of ion-button if disabled
# Bug Report

**Ionic version:**

[x] **4.x**

**Expected behavior:**

The 'disabled' rules (opacity: 1) should be applied.

**Steps to reproduce:**

1. Add disabled attribute to ion-button
2. Style it via pseudo or attribute selector of disabled
3. Css rules are not applied

**Related code:**

```
 <ion-button color="success" type="submit" [disabled]="true">
        LOG IN
 </ion-button>

When an ion-button is disabled, the following styles is used

.button-native[disabled] {
     cursor: default;
     opacity: .5;
     pointer-events: none;
}
```
```
/* Not applied */
ion-button[disabled],
ion-button[disabled="true"],
ion-button:disabled {
   --opacity: 1!important;
   opacity: 1!important;
}

/* Not applied */
.button-native[disabled] {
   --opacity: 1!important;
   opacity: 1!important;
}
```
**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0
   OS     : Windows 10
```

### PR DESCRIPTION
**Pull request by Ivnosing**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Opacity could not be set for disabled buttons.

Issue Number: fixes #16965 

## What is the new behavior?

Opacity of both default and disabled buttons can be overwritten in the host component with the CSS variable `--opacity`.

```scss
:host(.button-disabled) {
  --opacity: .5;
  pointer-events: none;
}
```

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

```html
<ion-button style="--opacity: 1" disabled>Disabled opacity: 1</ion-button>
```

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thanks for doing this so quickly! I made a small change to the test because we rely on the normal buttons in that test to not be customized, but the ones with opacity look good! I will merge this when the build is done. :tada:

**Comment by KillerCodeMonkey** [comment]
short question:

After upgrading to 4.5.0 the --opacity: .5 is set but does not change the opacity of the disable button at all

Could somebody check that?

The button is placed in `ion-buttons` as a `clear` button. Tested in firefox and chrome - so the `md` mode is activated.

**Comment by Ivnosing** [comment]
@KillerCodeMonkey I am being able to change the opacity of a disabled button in a fresh ionic project with the latest version:
image

The last two buttons are placed in `ion-buttons` with `fill="clear"`.

**Comment by KillerCodeMonkey** [comment]
okay, but your all your buttons look like solid buttons with different opacity 😉.

clear should be with a transparent background and reversed text color.

**Comment by Ivnosing** [comment]
@KillerCodeMonkey the last two are with `fill="clear"` (pay attention, where it says "DISABLED, OPACITY: DEFAULT" and "DISABLED, OPACITY: 0.65", below the third blue one).

Let me know if I'm not understanding well.

**Comment by KillerCodeMonkey** [comment]
check this out:

```HTML
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <div class="ion-padding">
    The world is your oyster.
    <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs/">docs</a> will be your guide.</p>
  </div>
</ion-content>

<ion-footer>
  <ion-toolbar>
    <ion-buttons>
      <ion-button fill="clear" color="primary" disabled>clear disabled</ion-button>
      <ion-button fill="solid" color="primary" disabled>solid disabled</ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-footer>
```

Bildschirmfoto 2019-06-17 um 13 36 50

as you can see the clear buttons do not have the default disabled opacity set ;).

**Comment by KillerCodeMonkey** [comment]
but maybe this is another bug. 🤔

**Comment by KillerCodeMonkey** [comment]
Nope working in 4.4.0 

Bildschirmfoto 2019-06-17 um 13 46 04

**Comment by KillerCodeMonkey** [comment]
i will create a pr

**Pull request merged**
