### PR TITLE
feat(item): add overflow css variable

### PR DESCRIPTION
**Pull request by anagstef**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Overflow on `ion-item` is set to `hidden` and cannot be changed.

Issue Number: #17670

## What is the new behavior?

`--overflow` css variable is now exposed and defaults to `hidden` as it was before.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by agroves333** [comment]
Thanks for the PR @anagstef! This is also what I need to render an autocomplete component with suggestions listed inside an `ion-item` component. Looking forward to this one being merged/published.

**Comment by liamdebeasi** [comment]
Thanks for the PR! Would you be able to add a test in `src/components/item/test/basic/index.html`? Thanks!

**Comment by brandyscarney** [comment]
Thanks for the PR! I did some testing and this could actually be solved using inheritance. I created a separate PR for this, but I can add you as a co-author if you don't see any issues with this: https://github.com/ionic-team/ionic/pull/18502

**Comment by anagstef** [comment]
If the issue is fixed in #18502 , then maybe there is no reason for the current PR to exist. Do your magic! 😄

**Comment by brandyscarney** [comment]
Thanks @anagstef! I added you as a co-author on the commit here: 8d2a47e8815167ef804c36fc3ec958ef413b76c0

This will make it into our `4.5.0` release which should be tomorrow if all goes as planned. 😁

**Pull request closed without merging**
