### PR TITLE
fix(item-reorder): auto-scroll fix while dragging

### PR DESCRIPTION
**Pull request by rakshans1**
#### Short description of what this resolves:

Reorder list auto-scrolls while dragging item instead of jumping to top of page.

#### Changes proposed in this pull request:

- Use scrollTop of content while dragging
- Update lastScrollPosition with changes in scroll top

**Ionic Version**: 3.x

**Fixes**: #12769, #13333

### CODE REVIEW

**Comment by Brunomiller** [comment]
Hello rakshans1. I tested the fix and it is really good. But I notice that you have to keep moving finger to keep list scrolling. If you drag over the list boundary and stop finger, the list stop to scroll. Can you help with this point? Thanks a lot.

**Comment by ggravand** [comment]
Thank for looking into this, absolutely amazing if we can get it fixed, we had almost given up. Pardon my ignorance, but can you describe how to test your fix? If I clone your fork and build ionic-angular and manually put this in my project's node_modules folder, I get some odd errors - is this how you are supposed to test it?

**Comment by rakshans1** [comment]
@ggravand run `gulp release.prepareReleasePackage` and you will get ionic-angular inside dist folder

**Comment by ggravand** [comment]
Thanks @rakshans1. Unfortunately I see no change in behavior and I have double checked the patch is in place :-(.

**Comment by ggravand** [comment]
@rakshans1 Thanks for the demo! It also behaves oddly in (latest Chrome and Firefox 58.0.1) - see attachment.

ionic-13333

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Comment by richie50** [comment]
@rakshans1  did they merge your pull request to v3. I'm confused as to what is going on with the PR.

**Comment by crascher** [comment]
Which Ionic Version I need to use to get the reorder work for long lists?

**Comment by donaldruby** [comment]
Can someone confirm whether this issue ( fix(item-reorder): auto-scroll fix while dragging ) is fixed in V3 or V4 or both ?

**Pull request closed without merging**
