### PR TITLE
fix(refresher): check for cancelable before preventing default

### PR DESCRIPTION
**Pull request by BoyeMagnus**
Add check before preventing event.

#### Short description of what this resolves:
Resolves the following [issue](https://github.com/ionic-team/ionic/issues/15256), where an error was thrown, because the event wasn't cancelable.

#### Changes proposed in this pull request:

- Add check before preventing the event

**Ionic Version**: Latest

**Fixes**: #15256

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you!

**Comment by BoyeMagnus** [comment]
No problem. Thanks for the merge 🙌

**Comment by mohamedsharaf** [comment]
the same issue exists in the ion-slides

  ionic v 4.1.1

**Comment by liamdebeasi** [comment]
Hi there,

Please open a new issue if you are running into an problem with `ion-slides`.

Thanks!

**Pull request merged**
