### PR TITLE
fix(alert): show scrollbars not by default - Fixes #14178

### LINKED ISSUE #14178: Scrollbars showing on alerts even when the content is not scrollable
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

On a desktop device:
- Add a favorite in the ionic-stencil conf app
- Remove that favorite
- Notice the confirmation alert has a scrollbar

scrollbar

**Expected behavior:**

There would not be a scrollbar since that content is not actually scrollable

**Steps to reproduce:**

On a desktop device:
- Add a favorite in the ionic-stencil conf app
- Remove that favorite
- Notice the confirmation alert has a scrollbar

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

### PR DESCRIPTION
**Pull request by paulstelzer**
#### Short description of what this resolves:
y Scrollbar will be showed to alert and action sheet although it's not needed. So I convert it to auto so the scrollbar will only be shown if needed

### Before
firefox_2018-12-16_11-31-52

### After
firefox_2018-12-16_11-31-58

**Fixes**: #14178

### CODE REVIEW

**Comment by brandyscarney** [comment]
Has this been tested on the scrollable options in Action Sheet? I'm not able to scroll them with this PR: http://localhost:3333/src/components/action-sheet/test/scrollable-options

You may need this PR to reproduce: https://github.com/ionic-team/ionic/pull/16789

**Comment by paulstelzer** [comment]
@brandyscarney I am not able to scroll with the master branch. So my PR is not the cause that there are no scrollbars ;)

Master branch:

chrome_2018-12-18_08-46-41

**Comment by brandyscarney** [comment]
So I'm seeing scrolling working fine on master in a browser (tested in chrome & safari):



However, I am seeing some weird things happening with press events interfering with scrolling in iOS and it sometimes not working.

**Comment by paulstelzer** [comment]
@brandyscarney Yeah scrolling is also fine with this PR, I thought you missed the scrolling bars

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
