### PR TITLE
docs(toolbar): fix end slot documentation

### PR DESCRIPTION
**Pull request by obedm503**
Description for `end` slot was the same as `start` slot.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Could you please run `npm run build` and push the changes?

**Comment by obedm503** [comment]
There were no changes to the code, just the jsdoc comment. Running the build command would not make a difference.

**Comment by brandyscarney** [comment]
@obedm503 The build command also builds the documentation which is why the build is failing here. 🙂 

Screen Shot 2019-04-22 at 6 10 57 PM

https://github.com/ionic-team/ionic/pull/18092/checks?check_run_id=107376740

**Comment by brandyscarney** [comment]
Thank you!

**Comment by obedm503** [comment]
Great! Sorry for the initial misunderstanding.

**Pull request merged**
