### PR TITLE
fix(content): calculate tabbarHeight correctly when inside multiple i…

### PR DESCRIPTION
**Pull request by metz0r**
…on-tabs

#### Short description of what this resolves:
See issue https://github.com/driftyco/ionic/issues/10978

#### Changes proposed in this pull request:

- 
-
-

**Ionic Version**: 2.3

**Fixes**: #10978

### CODE REVIEW

**Comment by manucorporat** [comment]
I don't think this is a good fix. Once _tabbarHeight is setted, it will not change anymore, that does not seem right

**Comment by metz0r** [comment]
@manucorporat Well, the same goes for _tabsPlacement as you can see right below it. If there's a better way to fix the issue (which I assume you read and recreated) I'd love to see that rather than a "doesnt seem right"-type of comment without any substance. The bug is clearly there and this works in the cases I've tested, and I guess I'll have to continue using my custom build of Ionic if you decide to just close this.

**Comment by manucorporat** [comment]
>Well, the same goes for _tabsPlacement as you can see right below it. 
no, _tabsPlacement is always reset: https://github.com/metz0r/ionic/blob/f15b9566cb13d83e095f11958173b0208604b1f8/src/components/content/content.ts#L661

I have explained why it does not seem right to me "Once _tabbarHeight is setted, it will not change anymore" and I gave you a change to explain the change, don't get me wrong.

I am sure it did work for you, don't get mad if I do not merge it automatically, we can't merge a fix to an issue (I believe it is a real one) if it will introduce a new one.

For example, what if some user hides the tabbar dynamically, it will not work since the `_tabbarHeight` variable is never reset.

Maybe, `_tabbarHeight` should always be reset to `null` or `undefined`.

**Comment by metz0r** [comment]
Thanks for clarifying, PR updated.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
