### PR TITLE
Fix : infinite-scroll in IOS not firing

### PR DESCRIPTION
**Pull request by MohammadWaleed**
#### Short description of what this resolves:
The infinite scroll wouldn't work as expected on IOS devices
when scrolling fast and leaving  the scroll to reach the end by itself 

#### Changes proposed in this pull request:

- Add new event listener in infiniteScroll that listens to scroll end

**Ionic Version**: 2.x / 3.x

**Fixes**: #11994

** Tested the fix on:
1. IPad Air 2  iOS : 11.1
2. Nexus 5x Android : 8.0

### CODE REVIEW

**Comment by longgt** [comment]
_escLsn was not defined.

**Comment by MohammadWaleed** [comment]
oops !! 
i forgot to define it, thanks for pointing that out @longgt 
i defined it now.

**Comment by mateusduraes** [comment]
Hello @lostdev 
it was released? Bacause i still having the same error. I've updated my ionic-angular dependence to 3.9.2, but no success.

Iphone 6s
IOS: 11.2

**Comment by lostdev** [comment]
Hi @mateusduraes,

I don't think so; the pull request is still open. Since this is such a small change, my workaround was to add these changes directly into the compiled version of infinite-scroll, and it's part of my build process to make sure the file is updated.

**Comment by mateusduraes** [comment]
@lostdev thank you, do you have an working example?

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Comment by MohammadWaleed** [comment]
Moved to https://github.com/ionic-team/ionic/pull/14160

**Pull request closed without merging**
