### PR TITLE
refactor(content): use observables instead of unsubscribe

### PR DESCRIPTION
**Pull request by masimplo**
This pull request is in reference to https://github.com/driftyco/ionic/commit/3a718de4632427cdf1a44e066bb559a6c28c6733#commitcomment-20529331

Make use of the RxJS API to clear subscriptions
when they are no longer needed, instead of using
subscription references to unsubscribe. take(1)
will clear the subscription after it has been used
exactly 1 times. TakeUntil will clear the subscription
when an event is emitted on the passed observable,
ie. ngOnDestroy has been called.

### CODE REVIEW

**Comment by masimplo** [comment]
BTW instead of `this._componentDestroyed.next(true);` you can also do `this._componentDestroyed.complete();` inside ngOnDestroy, as takeUntil works both with the emitted values and complete event of the notifier as stated in the docs:

> takeUntil subscribes and begins mirroring the source Observable. It also monitors a second Observable, notifier that you provide. If the notifier emits a value **or a complete notification**, the output Observable stops mirroring the source Observable and completes.

but thought it might be more confusing for some that haven't used Subjects a lot. In our codebase we use complete as it seems more semantically correct both because it will be never be emitting another value and the emitted value has no significance.

**Comment by manucorporat** [comment]
@masimplo the team is refactoring a lot stuff for the 3.0 release related with tree-shaking and lazy loading, we will review this PR after 3.0 branch is merged into master.

**Comment by masimplo** [comment]
Thanks for letting me know. Looking forward to 3.0!

**Comment by manucorporat** [comment]
@masimplo I am not working in the "build" team, and i am kind of worried about adding dependencies... it might break some tree-shaking stuff my colleagues are working on. I prefer to wait :)

But thanks for PR, i would love to use this a lot more across the framework, not only in content.ts

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
