### PR TITLE
Vue build fix: HTMLStencilElement & ionicons

### PR DESCRIPTION
**Pull request by zwacky**
Hey all
I wanted to use @ionic/core@4.6.0 but it wasn't buildable anymore with @ionic/vue.
Two problems:
1) HTMLStencilElement
-> aligned it with @ionic/react's usage of HTMLStencilElement

2) ionicons not present
-> I added the same behaviour like in the recently updated react one.

fyi: currently the package sits at `0.0.8-test` on master, but hasn't been published since 0.0.4.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures -> **lintings from previous components**

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
error 1 (related to HtmlStencilElement):
```
ERROR in /Users/zwacky/data/jw-app/node_modules/@ionic/vue/dist/types/interfaces.d.ts(40,40):
TS2304: Cannot find name 'HTMLStencilElement'.
ERROR in /Users/zwacky/data/jw-app/node_modules/@ionic/vue/dist/types/interfaces.d.ts(43,42):
TS2304: Cannot find name 'HTMLStencilElement'.
ERROR in /Users/zwacky/data/jw-app/node_modules/@ionic/vue/dist/types/util.d.ts(9,67):
TS2304: Cannot find name 'HTMLStencilElement'.
```

error 2 (related to ionicons):
```
"export 'ICON_PATHS' was not found in 'ionicons/icons'
```

Issue Number: #18640 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mhartington** [comment]
Whys there a package-lock file here? Can you remove that ?

**Comment by zwacky** [comment]
@mhartington of course! whoops, shouldn't be there.

**Comment by stevebering** [comment]
Is this solved another way? I am hitting the same issue when I do an npm install of @ionic/vue@0.0.4. Is there another way to solve this issue? Thanks.

**Comment by kisonay** [comment]
npm install @ionic/view:next should install v .0.0.9

**Comment by zwacky** [comment]
`@ionic/vue@next` should work. didn't spend too much time with it, had some minor issues still fyi.

**Comment by ShadeAJ1** [comment]
Can someone please look into this.

**Comment by ShadeAJ1** [comment]
I just added `import { HTMLStencilElement } from '@ionic/core';` to interfaces.ts and util.ts to fix the issue. It was done in the update f56fea6 but for some reason I didn't get it. Sorry.

**Pull request closed without merging**
