### PR TITLE
fix(a11y): add missing type attribute on buttons

### PR DESCRIPTION
**Pull request by 5im0n**
#### Short description of what this resolves:

Some linter as [a11y.css](http://ffoodd.github.io/a11y.css/) throw an error when button doesn't have type attribute

#### Changes proposed in this pull request:

- Add missing attribute type on every button where 
- `<button type="button"></button>`

**Ionic Version**: 2.x

### CODE REVIEW

**Comment by AmitMY** [comment]
Out of curiosity, wouldn't it be better to use `host` on `ion-button` instead of adding "mess" to the code?
 (Meaning, angular will add `type="button"` on all buttons that are `ion-button`, instead of manual labour)

**Comment by 5im0n** [comment]
I'm not fully agree with you.
You can have a `ion-button` with `type="submit"` or `type="reset"`, depending on the context where you use the button.
Angular already take tare of [ARIA](https://www.w3.org/TR/html-aria/) with role attribute for a11y.

**Comment by AmitMY** [comment]
@5im0n Sorry, I meant as a default, that can be changed if the user did add a type.

**Comment by manucorporat** [comment]
I was not aware of this, I thought the type was "button" by default, but looks like it is not...
https://www.w3schools.com/tags/att_button_type.asp

@5im0n  I agree with @AmitMY, this should be in the button component as a **default** type attribute.

**Comment by 5im0n** [comment]
All right, fine to me to write less code 😄 ! (It should be well specified in the documentation as default type)
On the other hand, we should think of removing the type button attribute in some template, like checkbox.js, radio-button... which is already set !

**Comment by manucorporat** [comment]
@5im0n do you plan to update the PR?

**Comment by 5im0n** [comment]
@manucorporat, to summarize the update:

1. Remove all `type` attribute on button in every component templates
2. The `ion-button` and `ion-fab` components take care of set default type: `type="button"`
    If type attribute is already set, do nothing.

Is that all ?

**Comment by manucorporat** [comment]
@5im0n exactly!

**Comment by 5im0n** [comment]
@manucorporat it should be good.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
