### PR TITLE
[Controllers] Custom  components

### PR DESCRIPTION
**Pull request by mfdeveloper**
#### Short description of what this resolves:
Allow pass **custom components** to some Ionic `Controllers`. This is great to more flexible customizations for components methods and HTML tags, when `present()` from controller. These changes expand the possibiliies, like pass custom components to `<ion-select>`.

For example, now is possible pass custom component by param, like this:

```ts
this.toastCtrl.create({
 title: 'This is my custom toast'
...
}, ToastCustomComponent)
```

#### Changes proposed in this pull request:

- Pass custom components by second parameter in some `Controller` classes;
- Added `CustomComponents` like example, used in unit/e2e tests
- Modified the `IonicModule` to get an `Array` of customized components.

**Ionic Version**:  2.x / 3.x

**Related with**: #12594 #12558 #10087 #11483

### CODE REVIEW

**Comment by mburger81** [comment]
This would be a very very usufull feature! Does it support also Load controller?
It would be helfpfull if we can adf on loading controll some cutom components.

Please merge this pr.
Thx

**Comment by mfdeveloper** [comment]
Yes @mburger81 , this PR includes `LoadingController` too. 

The ionic-team just tagged with **feature**, but, I don't know when this PR will be merged. So, whether you wish this changes by now, you can point for my fork in your `package.json` file. Something like this:

```js
 'ionic-angular': 'mfdeveloper/ionic-angular#custom-controller-components'
```

**Comment by mburger81** [comment]
Maybe you should resolve the conflicts for PR, still hoping in a fast merge of this PR

**Comment by mfdeveloper** [comment]
@mburger81 Thank you so much for your feedback. I've resolved the conflicts by now! :smile:

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
