### PR TITLE
fix(slide-gesture): RTL fix for slide-gesture

### PR DESCRIPTION
**Pull request by sijav**
#### Short description of what this resolves:
RTL fix for slide-gesture, this will resolve any problem with drag from right to left such as swipe to back, items slider, etc.

#### Changes proposed in this pull request:

- slide position minus new position instead of new position minus slide position

**Ionic Version**: 3.x

**Fixes**: #11211

### CODE REVIEW

**Comment by sijav** [comment]
this commit have a bug on pages with menu, I'll check and fix it.
however this will fix item-sliding too

**Comment by AmitMY** [comment]
@sijav Note that master's menu is buggy, so it might not be your fault.
I have been working on a fix for some time now, but it is not yet perfect, and I am not sure how to perfect it.
Mind having a look? https://github.com/driftyco/ionic/pull/11336

**Comment by sijav** [comment]
@AmitMY yes I know it's my fault I'm working on.
I think I know why menu is buggy ...

**Comment by sijav** [comment]
Menu has been fixed and after this merge and menu fix merge there won't be any bug that I could aware of.
So if you saw any, just let me know.

**Comment by brandyscarney** [comment]
Thank you! 🙂

**Comment by sijav** [comment]
@brandyscarney now that this got merge would you mind check these as well?
#11825 for item sliding
#11830 for menu
Without these item sliding and menu have bugs and won't function correctly

**Pull request merged**
