### PR TITLE
docs(virtual-scroll): escape code block in markDirtyTail

### PR DESCRIPTION
**Pull request by calahatras**
#### Short description of what this resolves:
Documentation for virtual-scroll

#### Changes proposed in this pull request:

- escape code block in markdown

**Ionic Version**:

**Fixes**: #

### CODE REVIEW

**Comment by manucorporat** [comment]
Looks like the core-clean test is faling, can you run `npm run build` and commit any change?

**Comment by brandyscarney** [comment]
I think this change needs to be updated in the component itself but it looks fine there so maybe it's a doc generator error? 

https://github.com/ionic-team/ionic/blob/master/core/src/components/virtual-scroll/virtual-scroll.tsx#L236-L240

**Comment by manucorporat** [comment]
oh right! mmm interesting, typescript is the one extraction the doc string...

**Comment by brandyscarney** [comment]
Thank you for the PR! Since this is a problem with the documentation generator, I created an issue here: https://github.com/ionic-team/stencil/issues/1314

**Comment by calahatras** [comment]
Alright cool, do you want me to delete the PR @brandyscarney or is this referenced somewhere?

**Pull request closed without merging**
