### PR TITLE
fix(animation): Do not remove opacity for outgoing element

### PR DESCRIPTION
**Pull request by liamdebeasi**
#### Short description of what this resolves:
Fixes an issue where opacity is removed on an outgoing element right before it is removed from the DOM.

This only appears in Angular applications, but due to the way the lifecycles work there I think it may be best to just not bother removing the opacity (since the element is going to be trashed anyways).

This change is only for iOS (and desktop Safari in responsive design mode), and I did not notice any adverse effects when testing on the conference app as well as using vanilla ionic components.

#### Changes proposed in this pull request:

- Remove `true` for outgoing animations, setting `clearProperyAfterTransition` to `false` 

**Ionic Version**:

**Fixes**: #16988

### CODE REVIEW

**Comment by brandyscarney** [comment]
How can I reproduce this? I tried using the conference app in Safari but I don't see it.

**Comment by liamdebeasi** [comment]
@brandyscarney If you navigate to a page and hit the back button, you should see the animation complete but then the header from the page you just navigated away from re-appear for a split second. Probably easiest to test on the latest `master`

**Comment by liamdebeasi** [comment]
Also this repo shows it pretty well: https://github.com/lucaslevin/trainer (person who created the issue posted it)

**Comment by brandyscarney** [comment]
@liamdebeasi Which test on `master`? I tried on the `nav/basic` one in Safari and didn't see it.

**Comment by liamdebeasi** [comment]
Ah sorry, this issue only shows up in Angular applications. (despite the fix being in `core`)

**Comment by brandyscarney** [comment]
I was able to reproduce this and confirm the fix in the `test-app` in the `angular/test/` directory using the tabs test. Looks to me. 👍

**Pull request merged**
