### PR TITLE
fix (ion-content): move slot="fixed" inside wrapper div

### PR DESCRIPTION
**Pull request by akshit-wwstay**
#### Short description of what this resolves:
Fix the visibility of the content when passed through slot "fixed". 

#### Changes proposed in this pull request:
- Move slot="fixed" inside the div wrapper, fixes the issue

**Ionic Version**: 4.10.3

**Fixes**: #17754

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! This fix will break the FAB functionality:

| `master` | `akshit-wwstay:ion-content-slot-fix` |
| ---| ---|
| localhost_3333_src_components_fab_test_basic(iPhone 6_7_8) (1) | localhost_3333_src_components_fab_test_basic(iPhone 6_7_8) (2) |

The fixed content needs to be outside of the scrolling div as it should not scroll with the page. I believe the solution to this bug may be to add the following css to `content.scss` but it would require further testing:

```
::slotted([slot="fixed"]) {
  position: absolute;
}
```

🙂

**Comment by DavidWiesner** [comment]
The problem is a missing z-index. When adding a z-index to the fixed slot, the text is visible again

**Comment by dalemugford** [comment]
> The problem is a missing z-index. When adding a z-index to the fixed slot, the text is visible again. By default the fixed slot is behind the scroll content. So instead of adding a div there should be set a z-index on the fixed slot or the fixed slot should move above the scroll slot.

I'm finding the reverse— divs with `slot="fixed"` are _always_ on top of `ion-content`, with no way to make them _below_ ion-content. This prevents UI choices like having a parallax header with a fixed image behind content that can scroll overtop.

**Comment by brandyscarney** [comment]
Thanks again for the PR! I added a PR here that should fix this: https://github.com/ionic-team/ionic/pull/19867

I'm going to close this as it has been merged. 🙂

**Pull request closed without merging**
