### PR TITLE
Broken link

### PR DESCRIPTION
**Pull request by amcastror**
#### Short description of what this resolves:
Just a broken link fix

#### Changes proposed in this pull request:

- Fixed broken link in slides documentation.
-
-

**Ionic Version**: 1.x / 2.x / 3.x / 4.x
Current.
**Fixes**: #
Fix broken link

### CODE REVIEW

**Comment by christopheelkhourysaradar** [comment]
You might wanna include the changes proposed in this PR

**Comment by amcastror** [comment]
@christopheelkhourysaradar, I've updated the description.

**Comment by brandyscarney** [comment]
Thank you! Could you instead make it point to the v3 source? https://github.com/ionic-team/ionic/blob/v3/src/components/slides/slides.ts

We are redoing the docs completely for v4. 🙂

**Comment by brandyscarney** [comment]
Actually just merged this change as part of an older PR: https://github.com/ionic-team/ionic/pull/14413

Thank you though!!

**Comment by amcastror** [comment]
;)

**Pull request closed without merging**
