### PR TITLE
feat(alert): use a custom component in an alert

### PR DESCRIPTION
**Pull request by mausibris**
#### Short description of what this resolves:

This adds the ability to provide a custom component to the alert controller, similar to popover. This gives the possibility to easily create small dialogs, where ionic provides the title and buttons and the client code just needs to provide the content view.

Example:

    alertController.create({
        title: "title",
        component: InnerComponent,
        navParams: {say: "hello"},
        buttons: [{
            text: "OK",
            handler: (component: InnerComponent) => this.doSomething(component)
        }]
    }).present();

    @Component({template: "inner component: {{text}}"})
    export class InnerComponent {
        text: string

        constructor(navParams: NavParams) {
            this.text = navParams.get("say")
        }
    }

customalarm

**Ionic Version**: 3.x

### CODE REVIEW

**Comment by manucorporat** [comment]
@mausibris this is perfect! and it works really well! I will try to merge it soon :)

Thanks a lot for the PR!!

**Comment by manucorporat** [comment]
I am adding a new API to create custom Alerts:

```ts
this.alertCtrl.create()
  .setTitle("My Alert")
  .setCustom(InnerComponent, {parameter: "hi", user: "ionic"})
  .present();
```

**Comment by mausibris** [comment]
looks good. I like it

**Comment by AmitMY** [comment]
@manucorporat Hi, is this planned for any time soon?

**Comment by mburger81** [comment]
Very beautiful and helpful feature

**Comment by danielsogl** [comment]
@mausibris can you fix the conflicts?

**Comment by mausibris** [comment]
@danielsogl I could do this by the end of the week. I'm traveling right now...

**Comment by mausibris** [comment]
I closed the PR accidentally (and then opened again).
Sorry if it's not appropriate, but I wanted to ask if the more likely comes into the 3.x version or in 4.x

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
