### PR TITLE
refactor(themes): combine background/color steps to one var

### LINKED ISSUE #16202: Ionic 4 theming: review stepped colors to remove some
Review the stepped colors to see if we can remove half of them and just have one set. Since background moves towards text and vice versa, they are the same in reverse. For example, instead of having:

```
--ion-background-color-step-700: #4d4d4d;

--ion-text-color-step-300: #4d4d4d;
```

we could just have:

```
--ion-color-step-3: #4d4d4d;
```

(naming is not decided on)

# Summary of Steps

## Background Color Steps

| Used               | Step                               | Value          |
|--------------------|------------------------------------|----------------|
| :white_check_mark: | `--ion-background-color-step-50`   | `#f2f2f2`      |
| :red_circle:       | `--ion-background-color-step-100`  | `#e6e6e6`      |
| :white_check_mark: | `--ion-background-color-step-150`  | `#d9d9d9`      |
| :red_circle:       | `--ion-background-color-step-200`  | `#cccccc`      |
| :white_check_mark: | `--ion-background-color-step-250`  | `#bfbfbf`      |
| :red_circle:       | `--ion-background-color-step-300`  | `#b3b3b3`      |
| :red_circle:       | `--ion-background-color-step-350`  | `#a6a6a6`      |
| :red_circle:       | `--ion-background-color-step-400`  | `#999999`      |
| :red_circle:       | `--ion-background-color-step-450`  | `#8c8c8c`      |
| :red_circle:       | `--ion-background-color-step-500`  | `#808080`      |
| :red_circle:       | `--ion-background-color-step-550`  | `#737373`      |
| :red_circle:       | `--ion-background-color-step-600`  | `#666666`      |
| :red_circle:       | `--ion-background-color-step-650`  | `#595959`      |
| :red_circle:       | `--ion-background-color-step-700`  | `#4d4d4d`      |
| :red_circle:       | `--ion-background-color-step-750`  | `#404040`      |
| :red_circle:       | `--ion-background-color-step-800`  | `#333333`      |
| :red_circle:       | `--ion-background-color-step-850`  | `#262626`      |
| :red_circle:       | `--ion-background-color-step-900`  | `#1a1a1a`      |
| :red_circle:       | `--ion-background-color-step-950`  | `#0d0d0d`      |
| :red_circle:       | `--ion-background-color-step-1000` | `#000000`      |

## Text Color Steps

| Used               | Step                               | Value          |
|--------------------|------------------------------------|----------------|
| :red_circle:       | `--ion-text-color-step-50`         | `#0d0d0d`      |
| :white_check_mark: | `--ion-text-color-step-100`        | `#1a1a1a`      |
| :white_check_mark: | `--ion-text-color-step-150`        | `#262626`      |
| :white_check_mark: | `--ion-text-color-step-200`        | `#333333`      |
| :red_circle:       | `--ion-text-color-step-250`        | `#404040`      |
| :red_circle:       | `--ion-text-color-step-300`        | `#4d4d4d`      |
| :red_circle:       | `--ion-text-color-step-350`        | `#595959`      |
| :white_check_mark: | `--ion-text-color-step-400`        | `#666666`      |
| :white_check_mark: | `--ion-text-color-step-450`        | `#737373`      |
| :red_circle:       | `--ion-text-color-step-500`        | `#808080`      |
| :white_check_mark: | `--ion-text-color-step-550`        | `#8c8c8c`      |
| :white_check_mark: | `--ion-text-color-step-600`        | `#999999`      |
| :white_check_mark: | `--ion-text-color-step-650`        | `#a6a6a6`      |
| :red_circle:       | `--ion-text-color-step-700`        | `#b3b3b3`      |
| :red_circle:       | `--ion-text-color-step-750`        | `#bfbfbf`      |
| :white_check_mark: | `--ion-text-color-step-800`        | `#cccccc`      |
| :red_circle:       | `--ion-text-color-step-850`        | `#d9d9d9`      |
| :red_circle:       | `--ion-text-color-step-900`        | `#e6e6e6`      |
| :red_circle:       | `--ion-text-color-step-950`        | `#f2f2f2`      |
| :red_circle:       | `--ion-text-color-step-1000`       | `#ffffff`      |

## Proposed Combined Steps

| Used               | Step                    | Value          | Default Mix Amount |
|--------------------|-------------------------|----------------|--------------------|
| :white_check_mark: | `--ion-background-color`| `#ffffff`      | 0%                 |
| :white_check_mark: | `--ion-color-step-50`   | `#f2f2f2`      | 5%                 |
| :red_circle:       | `--ion-color-step-100`  | `#e6e6e6`      | 10%                |
| :white_check_mark: | `--ion-color-step-150`  | `#d9d9d9`      | 15%                |
| :white_check_mark: | `--ion-color-step-200`  | `#cccccc`      | 20%                |
| :white_check_mark: | `--ion-color-step-250`  | `#bfbfbf`      | 25%                |
| :red_circle:       | `--ion-color-step-300`  | `#b3b3b3`      | 30%                |
| :white_check_mark: | `--ion-color-step-350`  | `#a6a6a6`      | 35%                |
| :white_check_mark: | `--ion-color-step-400`  | `#999999`      | 40%                |
| :white_check_mark: | `--ion-color-step-450`  | `#8c8c8c`      | 45%                |
| :red_circle:       | `--ion-color-step-500`  | `#808080`      | 50%                |
| :white_check_mark: | `--ion-color-step-550`  | `#737373`      | 55%                |
| :white_check_mark: | `--ion-color-step-600`  | `#666666`      | 60%                |
| :red_circle:       | `--ion-color-step-650`  | `#595959`      | 65%                |
| :red_circle:       | `--ion-color-step-700`  | `#4d4d4d`      | 70%                |
| :red_circle:       | `--ion-color-step-750`  | `#404040`      | 75%                |
| :white_check_mark: | `--ion-color-step-800`  | `#333333`      | 80%                |
| :white_check_mark: | `--ion-color-step-850`  | `#262626`      | 85%                |
| :white_check_mark: | `--ion-color-step-900`  | `#1a1a1a`      | 90%                |
| :red_circle:       | `--ion-color-step-950`  | `#0d0d0d`      | 95%                |
| :white_check_mark: | `--ion-text-color`      | `#000000`      | 100%               |

### PR DESCRIPTION
**Pull request by brandyscarney**
#### Short description of what this resolves:
Combines the background color and text color steps since they are the same in opposite directions. Implements the proposed steps from #16202 

| Used               | Step                    | Value          | Default Mix Amount |
|--------------------|-------------------------|----------------|--------------------|
| :white_check_mark: | `--ion-background-color`| `#ffffff`      | 0%                 |
| :white_check_mark: | `--ion-color-step-50`   | `#f2f2f2`      | 5%                 |
| :red_circle:       | `--ion-color-step-100`  | `#e6e6e6`      | 10%                |
| :white_check_mark: | `--ion-color-step-150`  | `#d9d9d9`      | 15%                |
| :white_check_mark: | `--ion-color-step-200`  | `#cccccc`      | 20%                |
| :white_check_mark: | `--ion-color-step-250`  | `#bfbfbf`      | 25%                |
| :red_circle:       | `--ion-color-step-300`  | `#b3b3b3`      | 30%                |
| :white_check_mark: | `--ion-color-step-350`  | `#a6a6a6`      | 35%                |
| :white_check_mark: | `--ion-color-step-400`  | `#999999`      | 40%                |
| :white_check_mark: | `--ion-color-step-450`  | `#8c8c8c`      | 45%                |
| :red_circle:       | `--ion-color-step-500`  | `#808080`      | 50%                |
| :white_check_mark: | `--ion-color-step-550`  | `#737373`      | 55%                |
| :white_check_mark: | `--ion-color-step-600`  | `#666666`      | 60%                |
| :red_circle:       | `--ion-color-step-650`  | `#595959`      | 65%                |
| :red_circle:       | `--ion-color-step-700`  | `#4d4d4d`      | 70%                |
| :red_circle:       | `--ion-color-step-750`  | `#404040`      | 75%                |
| :white_check_mark: | `--ion-color-step-800`  | `#333333`      | 80%                |
| :white_check_mark: | `--ion-color-step-850`  | `#262626`      | 85%                |
| :white_check_mark: | `--ion-color-step-900`  | `#1a1a1a`      | 90%                |
| :red_circle:       | `--ion-color-step-950`  | `#0d0d0d`      | 95%                |
| :white_check_mark: | `--ion-text-color`      | `#000000`      | 100%               |

Closes #16202

:warning: Requires an update to documentation

### CODE REVIEW

**Comment by ptitjes** [comment]
I'm sorry I might be a little late. But why using three digits ? Those could be numbered 5, 10, 15, 20, ... which is the actual default mix percentage. That would be far more natural!

**Comment by brandyscarney** [comment]
@ptitjes Honestly it was just something we decided on to match how Material Design does their color variant system. https://material.io/design/color/the-color-system.html#color-theme-creation

screen shot 2018-11-30 at 6 03 02 pm

While the defaults that we provide are a percentage mixed, you could actually pass whatever value you wanted to this.

In an ideal world these wouldn't even be user facing, but unfortunately we have no way to _easily_ manipulate the background/text CSS variables without something like [color-mod](https://www.w3.org/TR/css-color-4/#modifying-colors) right now. 

I started updating the documentation for this already, but I think at some point it would be nice to have a generator for this so it is something the user can just copy/paste without having to figure it all out: https://github.com/ionic-team/ionic-docs/pull/211

**Comment by ptitjes** [comment]
I see. Just to sure to understand when you say it should not be user facing, the exception is when user is defining themes right ?

**Comment by ptitjes** [comment]
I ask, because it was not clear for from the documentation. I cooked that https://github.com/cabasvert/cabasvert/blob/master/packages/client/src/theme/theme-dark.scss for my application, but I missed some clear guidelines.

**Comment by brandyscarney** [comment]
Yes currently it is a public API because it isn't possible for us to manipulate the color passed in to `--ion-background-color` or `--ion-text-color` at runtime. So this is user facing because of that. These are mainly there for full theming control. If you change the background of your application to a shade like `#f8f8f8`, it's unlikely that the places these stepped colors are used will even need to be updated, since it is so close to to the default it _might_ look fine.

However, if you're using a dark theme (which I see by your latest comment you are) it will be noticeable without the stepped colors in instances such as loading where it uses a shade of the background color and not the exact background color. 

I'd like to have a theme generator though that automatically does the mix by default, since it isn't required to use Sass anymore. 

Does my documentation [from this PR](https://github.com/ionic-team/ionic-docs/pull/211/files) clear it up at all?

screen shot 2018-11-30 at 6 38 23 pm
 
I'm trying really hard to explain why these are needed without it being too much or too confusing. I'm open to any ideas, too. 😅

**Comment by paulstelzer** [comment]
Understandable. I created a mixin to not write every step ;)

Inside a theme.scss (or  just global.scss) put:

```
@mixin step-color($text-color, $background-color) {
    $step: 5;
    @while $step <= 95 {
        --ion-color-step-#{$step*10}: #{mix($text-color, $background-color, percentage($step / 100))};
        $step: $step+5;
    }
}
```

And then just add to, for example a dark theme

```
:root {
   .dark-theme {
        $text-color: #fff;
        $background-color: #000;
        @include step-color($text-color, $background-color);
        --ion-background-color: #{$background-color};
        --ion-text-color: #{$text-color};
    }
}
```

And then it looks like this ->

color-switcher

**Comment by ptitjes** [comment]
@brandyscarney Yes, the documentation indeed is more clear like this. Thank you very much for your detailed answer.

@paulstelzer That's great! If you don't mind I will steal you your mixin. 😁

**Comment by paulstelzer** [comment]
@ptitjes that was the reason I shared it ;)

**Comment by brandyscarney** [comment]
I also added a generator to the docs for pure css 🙂

**Pull request merged**
