### PR TITLE
Do not consider search string when calculating view equality

### PR DESCRIPTION
**Pull request by lincolnthree**
#### Short description of what this resolves:
This change is required to prevent the URL search string from being "obliterated" on view changes, and to prevent the search string from impacting view equality and when resolving views based on URL deep links (@IonicPage segments).

#### Changes proposed in this pull request:

-
-
-

**Ionic Version**: 1.x / 2.x / 3.x
3.x
**Fixes**: #
https://github.com/ionic-team/ionic/issues/12328

This may not be a complete fix for the issue, as I have not been able to fully test the original poster's requirements, but it meets some of the needs and should happen in order to support traditional browser-based search string behavior anyway.

### CODE REVIEW

**Comment by lincolnthree** [comment]
Just checking in on this. Last I heard this was basically good to go but not sure where things stand. Thanks!

**Comment by lincolnthree** [comment]
@danbucholtz ^ ?

**Comment by lincolnthree** [comment]
@brandyscarney  Any update on this? Last I heard it was good to go, several months now gone by :)

**Comment by lincolnthree** [comment]
Bump.

**Comment by daem0ndev** [comment]
Bump! We are in heavy need for this functionality to support oauth2 callbacks on our app. Is there any issue with this PR and why we cant get this merged? I'm happy to assist in testing and troubleshooting.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
