### PR TITLE
fix(card): don't remove border on inputs

### LINKED ISSUE #11640: Input field underline missing when inside ion-card
**Ionic version: **3.2.1**

**I'm submitting a **Bug Report**

**Current behavior:**
When I put an `<ion-input>` inside an `<ion-card>` The bottom border that acts as an underline is being overwritten with some [core css found here](https://github.com/driftyco/ionic/blob/master/src/components/card/card.md.scss#L150)
 **when using the `md` or `default` modes.** 

```
.card-md .item-md.item-block .item-inner {
  border: 0;
}
```
The password field has a border but only because it is also the last child of a list.
screen shot 2017-05-12 at 4 17 29 pm

Code to produce:
```
<ion-card class="contentBox">
            <ion-card-header>
              <h3>Login</h3>
            </ion-card-header>
            <ion-card-content>
            <ion-list>
              <ion-item>
                <ion-label floating>Email</ion-label>
                <ion-input type="email"></ion-input>
              </ion-item>
              <ion-item>
                <ion-label floating>Password</ion-label>
                <ion-input type="password"></ion-input>
              </ion-item>
            </ion-list>
            </ion-card-content>
</ion-card> <!-- contentBox -->
```

**Expected behavior:**
Should leave the underline intact
Plunker: http://plnkr.co/edit/hSbLqd?p=preview

### PR DESCRIPTION
**Pull request by iget-master**
#### Short description of what this resolves:

This resolves the issue #11640 where the border bottom on ion-item disappears when used inside an `ion-card`

#### Changes proposed in this pull request:

- Updated `ion-card` MD scss

**Ionic Version**: 3.x

**Fixes**: #11640

### CODE REVIEW

**Comment by AmitMY** [comment]
Thanks for this PR.
Can you please change the title to: `fix(card): don't remove border on inputs` or something of that sort?

**Comment by iget-master** [comment]
@AmitMY Done! :)

**Comment by iget-master** [comment]
?

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
