### PR TITLE
feat(toast): add white-space variable for toast message

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://github.com/ionic-team/ionic/issues/20727

## What is the new behavior?

- Changed the wrapping for the toast message from `pre-wrap` to `pre-line`.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Why not use `"normal"`?

**Comment by liamdebeasi** [comment]
We can use `normal`, but `pre-line` is the closest to `pre-wrap` in terms of behavior (minus collapsing whitespace) so I was concerned about introducing unexpected breaking changes by using `normal`.

**Comment by RafaelKr** [comment]
Would it be an option to make it customizable defaulting to `pre-wrap` for now and switching to `normal` when 5.1.0 is released?

**Comment by brandyscarney** [comment]
No matter what we change it to it may be an unexpected change to users. We're currently respecting all white-space, so take the following message:

```
message: `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor <b>incididunt</b> ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation <b>ullamco</b> laboris nisi ut aliquip ex ea commodo consequat.

`,
```

In `master`, using `pre-wrap`:

toast-pre-wrap

Changing to `pre-line`:

toast-pre-line

Changing to `normal`:

toast-normal

Judging by the Material Design specs I don't think we should be respecting the beginning or ending lines:

Screen Shot 2020-03-10 at 12 22 07 PM

They don't have any two-line examples but they do use `white-space: normal`: https://material-components.github.io/material-components-web-catalog/#/component/snackbar

**Comment by RafaelKr** [comment]
Wouldn't it make more sense to change the default to `normal` when it goes into 5.1.0 anyways?

**Comment by brandyscarney** [comment]
@RafaelKr Minor releases are for adding features. Fixing an issue to match the spec would be considered a bug fix and can go into a patch release. We only consider breaking changes things that remove from or change the public API, which would be a major release. This file is a general overview of our API: https://github.com/ionic-team/ionic/blob/master/core/api.txt

In this case we are going to be adding a CSS variable to the public API so it can be changed but leaving it as it is for now.

**Comment by RafaelKr** [comment]
@brandyscarney Oh right, it could break things for others. Then I'm fine with the current way how to do it :)
Maybe something to put onto the v6 Milestone. Although it's probably still a long time until v6. 
Do you have a release cycle or are things ready when they're ready?

**Comment by brandyscarney** [comment]
@RafaelKr Our normal release cycle is every 2 weeks at a minimum for feature (minor) releases. Patch releases we were releasing on the same cycle, but with Ionic 5 being such a big release we have been trying to get them out faster to get fixes in. At the moment we don't have big features planned so our main focus has been on fixes. This document is a little outdated since we were doing minor releases sooner: https://ionicframework.com/docs/intro/versioning

**Pull request merged**
