### PR TITLE
fix(datetime): adjust default for timezone offset

### PR DESCRIPTION
**Pull request by patrickmcd**
The default "now" time doesn't take into account the local timezone offset.

https://stackblitz.com/edit/ionic-qzk7rn

### CODE REVIEW

**Comment by Simpler1** [comment]
Hi Patrick,

This change is incorrect.  The "Z" at the end means UTC (or zero time zone offset).

If you want to adjust for timezone, you would replace the "Z" with the actual offset such as "-04:00".
See [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

A related problem is that <ion-datetime> incorrectly appends a "Z" even though it is local time.

**Comment by Simpler1** [comment]
If you add the `.slice(0,-1)` (to take off the `Z` suffix) after subtracting the timezone offset, it would be better than what is currently there.  It would at least be considered a local time (not timezone specified).

Ideally `ion-datetime` would store the data back with the current timezone offset instead of just truncating it.
(i.e. `2017-10-04T16:57:52.321-04:00`)

**Comment by patrickmcd** [comment]
Thanks @Simpler1,

I had the slice commented out in my original Stackblitz because I didn't see a difference in the functionality and opted for the slightly simpler code.

Since we're slicing, we might as well slice off the fractional seconds too because they can't be entered in `displayFormat` or `pickerFormat`.

**Comment by dedd1993** [comment]
use moment as ionic recomends on its documentationn (https://ionicframework.com/docs/api/components/datetime/DateTime/#advanced-datetime-validation-and-manipulation)

 1. Open console at root proyect and install moment: <code>npm install moment --S</code>.
 2. Import moment in component file: <code>import moment from 'moment';</code>.
 3. Set value of model variable: <code>this.myDate = moment().format()</code>.

**Comment by mhartington** [comment]
Closing for now. Dates in JS are a can of worms. Best bet is to use Moment or even better, Date-fns. Thanks!

**Pull request closed without merging**
