### PR TITLE
fix(datetime): recalculate day column when month is changed

### PR DESCRIPTION
**Pull request by liamdebeasi**
#### Short description of what this resolves:
This PR is meant to combine the changes proposed by #17562 and #14434 and to clean up the code a bit. Additionally, this PR also introduces more tests

#### Changes proposed in this pull request:

- Add `onIonPickerColChange` event to `ion-picker-column` to allow the datetime component to be aware of the need to recalculate day values 
- Add tests for `ion-picker-column`
- Add generic test utilities for interaction and listening for evens.

**Ionic Version**:

**Fixes**:
#14233
#14732
#15452
#15794
#16733
#17060 
#17510
#17521

### CODE REVIEW

**Comment by zhiwo** [comment]
> #### Short description of what this resolves:
> This PR is meant to combine the changes proposed by #17562 and #14434 and to clean up the code a bit. Additionally, this PR also introduces more tests
> 
> #### Changes proposed in this pull request:
> * Add `onIonPickerColChange` event to `ion-picker-column` to allow the datetime component to be aware of the need to recalculate day values
> * Add tests for `ion-picker-column`
> * Add generic test utilities for interaction and listening for evens.
> 
> **Ionic Version**:
> 
> **Fixes**:
> #14233
> #14732
> #15452
> #15794
> #16733
> #17060
> #17510
> #17521

I try,but I don't know how update right column,I try  this.validate(picker) ,not find the method

**Comment by liamdebeasi** [comment]
For help implementing your code, please post your question on our [forum](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!

**Comment by zhiwo** [comment]
picker.addEventListener('ionPickerColChange', async (event: any) => {
       const data = event.detail;
       const colSelectedIndex = data.selectedIndex;
       const colOptions = data.options;

        const changeData: any = {};
       changeData[data.name] = {
         value: colOptions[colSelectedIndex].value
       };

        this.updateDatetimeValue(changeData);
       const columns = this.generateColumns();

        picker.columns = columns;

        await this.validate(picker);
     });

After rebinding the value，Column can't refresh, And I try validate method，but not find the method，I need you help！

Thanks!

**Comment by zhiwo** [comment]
image

**Comment by liamdebeasi** [comment]
Hi there,

We do not provide support debugging your code. Like I mentioned previously, the forums and our slack (links in my previous comment) are the best places to post this question. 

If you feel you have encountered a bug in Ionic's code, feel free to open a new issue. Please be sure to attach a code reproduction. That will help us reproduce the issue faster.

**Pull request merged**
