### PR TITLE
fix(toast): allow to change position start/end of toast

### PR DESCRIPTION
**Pull request by entom**
#### Short description of what this resolves:
This allows user to set start and/or end position of toast-wrapper by using --start, --end.

#### Changes proposed in this pull request:

-
-
-

**Ionic Version**:
4.2.0
**Fixes**: #17854

### CODE REVIEW

**Comment by entom** [comment]
Ok, no problem. I have created some tests.

**Comment by liamdebeasi** [comment]
Hey there!

Sorry for the delay in reviewing this. We had an update to toast that we were trying to get merged in, and unfortunately there were some merge conflicts created as a result.

Would you be able to resolve the conflicts? After that I can take another look.

Thanks! 🙂

**Comment by entom** [comment]
Ok, no problem. Thanks for response. I have resolved conflicts and merged changes.

**Comment by brandyscarney** [comment]
Thanks for the PR! We made some changes that I just wanted to make aware, the big one being renaming the following:

```
left -> start
right -> end
```

The main reason for this is because in RTL applications the `left` is actually the `right`, so in many places we are using `start` and `end` now for RTL support. 🙂 

I made a couple changes to the implementation but this is good to go! We can merge it once the build passes.

**Comment by brandyscarney** [comment]
Merged, thank you!!

**Pull request merged**
