### PR TITLE
[Vue] Add polyfills

### PR DESCRIPTION
**Pull request by michaeltintiuc**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Without calling the `applyPolyfills` function MS Edge fails with the following error:
`Unhandled promise rejection TypeError: Unable to get property 'get' of undefined or null reference`

## What is the new behavior?

MS Edge no longer fails

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by zwacky** [comment]
I wonder what `applyPolyfills()` actually does, because in the source it's [simply an empty Promise.resolve](https://github.com/ionic-team/ionic/blob/84e306c1a682f1dec580139f42b5f253a7ec6f60/core/scripts/cdn-loader.js#L2).

Is that portion added through the build process?

**Comment by manucorporat** [comment]
@zwacky that is only for CDN use case, ie, loading ionic in stackblitz for example.

**Comment by zwacky** [comment]
I can't fully understand why this little code, which is merely a `return Promise.resolve()` breaks MS Edge user from rendering at all 🤔

**Comment by michaeltintiuc** [comment]
Based on my debug results, this is the function that is actually being called:
Loaded from `@ionic/core/loader/index.mjs` and the contents being in `@ionic/core/dist/esm/polyfills/index.js`
```
export function applyPolyfills() {
  var win = window;

  var promises = [];

  if (!win.customElements || (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove))) {
    promises.push(import('./dom.js'));
  }

  function checkIfURLIsSupported() {
    try {
      var u = new URL('b', 'http://a');
      u.pathname = 'c%20d';
      return (u.href === 'http://a/c%20d') && u.searchParams;
    } catch(e) {
      return false;
    }
  }

  if (
    'function' !== typeof Object.assign || !Object.entries ||
    !Array.prototype.find || !Array.prototype.includes ||
    !String.prototype.startsWith || !String.prototype.endsWith ||
    (win.NodeList && !win.NodeList.prototype.forEach) ||
    !win.fetch ||
    !checkIfURLIsSupported() ||
    typeof WeakMap == 'undefined'
  ) {
    promises.push(import('./core-js.js'));
  }
  if (!(win.CSS && win.CSS.supports && win.CSS.supports('color', 'var(--c)'))) {
    promises.push(import('./css-shim.js'));
  }
  return Promise.all(promises);
}
```

**Pull request closed without merging**
