### PR TITLE
feat(tabs): scrollable tabs for MD

### PR DESCRIPTION
**Pull request by manucorporat**
#### Short description of what this resolves:

jul-03-2016 21-23-59

Closes https://github.com/driftyco/ionic/issues/5101

### CODE REVIEW

**Comment by brandyscarney** [comment]
This looks good, but there seem to be some issues with the newly added box-shadow. See this gif: http://g.recordit.co/NIdrXYtQfr.gif

I'm able to scroll the tabs up and down, and the box-shadow cuts off midway through.

**Comment by brandyscarney** [comment]
@manucorporat Can you fix the merge conflicts on this, and also we need to find a default behavior for iOS and windows since this is only added for MD mode.

**Comment by NoNameProvided** [comment]
Do we have any problem except the merge conflict which prevent this from being merged?

**Comment by brandyscarney** [comment]
@NoNameProvided Yes, there are quite a few things that need to be done before we can get this merged. Please see my comment here for more info: https://github.com/driftyco/ionic/issues/5101#issuecomment-255198026

**Comment by brandyscarney** [comment]
Closing this, we need to fix Segment to have this behavior.

**Comment by NoNameProvided** [comment]
@brandyscarney can you point us to a ticket or PR where we can subscribe for updates on this?

**Comment by newsof1111** [comment]
swiped tabs in ionic 3

https://www.youtube.com/watch?v=mlwVsr0_iO8&t=2s
ionic3swipedtabs

**Pull request closed without merging**
