### PR TITLE
feat(range): allow fractional steps

### PR DESCRIPTION
**Pull request by AmitMY**
WIP, it works, but snaps fractional values even without snap.

#### Short description of what this resolves:
I want a range from 0.5 to 1.5 (step: 0.1), and while I can use an intermediate variable, with range 1-15, I can't use pin for that.

#### Changes proposed in this pull request:
- Don't round the step

**Ionic Version**: 3.x

Closes: https://github.com/ionic-team/ionic/issues/6812 https://github.com/ionic-team/ionic/pull/9098

### CODE REVIEW

**Comment by PAFsec** [comment]
Hello,

Your fix does not work as the value is after rounded again later in the code.

this issue is already referenced here #6812 and #9098

**Comment by AmitMY** [comment]
I like that, thanks!
That solution does not fully work as well, as there is a `Math.round` on step, and I don't like needing to specify resolution. I changed my solution a bit, to incorporate the `resolution`, but it self calculates it so there is no need to give it as an input.
I also think that fractional `min` and `max` are a good thing, which that solution does not do.

**Comment by PAFsec** [comment]
Ah, true, did not think of that !

Is it working well with your fractionial step ? Because with the solution given in the other issue, I stated that there was a kind of shaky behavior on the knob.

Thanks,

**Comment by AmitMY** [comment]
@PAFsec Yeah, this is not perfect, it "snaps fractional values even without snap" weirdly, but I think that is probably a small fix.. would love some team feedback on this

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
