### PR TITLE
feature/fix(content): expose custom scrollbar styling via css variables

### PR DESCRIPTION
**Pull request by lincolnthree**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x ] Build (`npm run build`) was run locally and any changes were pushed
- [x ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x ] Bugfix (this is both a bug and a feature since it breaks app styling on many platforms)
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://github.com/ionic-team/ionic/issues/17685

## What is the new behavior?

Scrollbars in ion-content.inner-scroll can now be styled via css variables exposing multi-browser supported configuration elements. As there is no way to provide a default value in chrome for scrollbar styling (because default styles are applied only if no values are set -- before variable compute time) a toggle has been built in to enable/disable custom styles instead. This can be improved when the CSS scrollbars spec gets ratified and adopted.
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

Showing custom styles enabled (and provided with some ugly values) and disabled (default.) This can also be seen in the ion-content tests.

image

### CODE REVIEW

**Comment by lincolnthree** [comment]
This is my first PR. I would love feedback on this. Thanks!

**Comment by lincolnthree** [comment]
Please let me know if anything needs to change. I merged master to try to get things up to date.

**Comment by liamdebeasi** [comment]
Thanks for the PR! We appreciate all of the hard work you put into creating this. After discussion with the team, we have decided to not move forward with this PR.

Please see https://github.com/ionic-team/ionic/issues/17685#issuecomment-587633556 for a more detailed explanation.

**Comment by labmux** [comment]
Still no solution? How can one of the most popular hybrid frameworks not offer a simple solution to hiding scrollbars?

**Pull request closed without merging**
