### PR TITLE
Register multiple callbacks to modals

### PR DESCRIPTION
**Pull request by iwantwin**
#### Short description of what this resolves:
These changes allows for registering multiple listeners for onDidDismiss and onWillDismiss. It is backwards compatible and does not require any changes to registering.

This is useful for situations where you would want to build a provider (for example 'modalmanager') that serves a modal to another provider, where both providers want to register to onDidDismiss or onWillDismiss.

#### Changes proposed in this pull request:

- Register multiple callbacks to onDidDismiss
- Register multiple callbacks to onWillDismiss

**Ionic Version**: 3.x

**Fixes**: #

### CODE REVIEW

**Comment by AmitMY** [comment]
Any reason not to use EventEmitters instead? (already known to work, has support for subscribing and unsubscribing, and everyone knows them)

**Comment by iwantwin** [comment]
You've got a good point there. I thought it would be best to have backwards compatibility here, but we could also implement it both ways: support the current way and have extra event emitters. This way it would also not break existing apps relying on the current behaviour.

Will update my code accordingly within 2 days!

**Comment by iwantwin** [comment]
I did update my code to do the changes I hoped for, but also be fully backwards compatible for apps that rely on the current behaviour.

Therefore, the branch currently has the following changes:
- Register multiple callbacks to onDidDismiss
- Register multiple callbacks to onWillDismiss
- Fully backwards compatible

Example code:
```
let modal = new MultiModal( LoginPage, {}, {} );
//Old way of registering
modal.onDidDismiss( (data: any, role: string) => {
    console.log('the old way of registering an event, still works as this is fully backwards compatible!');
} );
//New way of registering (multiple/extra handlers)
modal.onDidDismiss().subscribe((event: (data: any, role: string)) => {
    console.log('the new way of registering an event, handler 1!');
} );
modal.onDidDismiss().subscribe((event: (data: any, role: string)) => {
    console.log('the new way of registering an event, handler 2!');
} );
```

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
