### PR TITLE
RFC: Vue.JS support

### PR DESCRIPTION
**Pull request by moduscreate**
#### Short description of what this resolves:
Use Ionic in Vue applications. This package integrates the work done in the [`ionic-vue`](https://github.com/ModusCreateOrg/ionic-vue) library into the Ionic core.

#### Changes proposed in this pull request:

- Add `@ionic/vue` package
- `vue-router` integration
- Ionic API connector
- Register Ionic web components with Vue

**Ionic Version**: 4.x

## Installing

Assuming that the app already bundles `vue` and `vue-router` via Vue CLI or manually, install Ionic with `npm`

```shell
npm install @ionic/vue
```

### Dependencies

* `@ionic/core`
* `vue`
* `vue-router`

## Using in a Vue application

`@ionic/vue` uses `@ionic/core` internally so a developer would only have register the Ionic plugins for Vue.

```js
import Vue from 'vue'
import { IonicVueRouter, IonicAPI } from '@ionic/vue'
import Home from './Home.vue'
import Page from './Page.vue'

Vue.use(IonicVueRouter)
Vue.use(IonicAPI)

new Vue({
  router: new IonicVueRouter({
    routes: [{ path: '/', component: Home }, { path: '/page', component: Page }],
  }),
}).$mount('ion-app')
```

Ionic requires a root element of `ion-app` in HTML.

`IonicVueRouter` requires `ion-vue-router` element in order to render the components.

```html
<!DOCTYPE html>
<html lang="en">
  <head>...</head>

  <body>
    <ion-app>
      <ion-vue-router/>
    </ion-app>
  </body>
</html>
```

### IonicAPI

`IonicAPI` abstracts DOM interaction of Ionic UI components inside a Vue application and can be used via `this.$ionic`.

#### Alert Controller usage

```js
this.$ionic.alertController
  .create({
    header: 'Notification',
    subHeader: null,
    message: 'Hello World',
    buttons: ['Bye'],
  })
  .then(a => a.present())
```

#### Loading Controller usage
```js
this.$ionic.loadingController.create()
  .then(l => {
    l.present()
    setTimeout(function() {
      l.dismiss()
    }, 1000)
  })
```

#### Menu Controller usage
```js
this.$ionic.menuController.toggle()
```

#### Modal Controller usage
Also supports lazy loading components
```js
this.$ionic.modalController.create({
  component: {
    template: `
      <div>
        <ion-content padding>
        <h1>Howdy!</h1>
        </ion-content>
      </div>`,
  }
})
.then(m => m.present())
```

#### Popover Controller usage
Also supports lazy loading components
```js
this.$ionic.popoverController.create({
  component: {
    template: `
      <ion-list>
        <ion-list-header>
          <ion-label>Ionic</ion-label>
        </ion-list-header>
        <ion-item>Learn Ionic</ion-item>
        <ion-item>Documentation</ion-item>
        <ion-item>Showcase</ion-item>
        <ion-item>GitHub Repo</ion-item>
    </ion-list>`,
  },
  translucent: true,
  event
})
.then(p => p.present())
```

#### Toast Controller usage
```js
this.$ionic.toastController.create({
  message: 'Here\'s to IonicVue!',
  showCloseButton: true,
  position: 'top',
  closeButtonText: 'Done'
})
.then(t => t.present())
```

IonicVueAPI supports the following Ionic controllers and a demo is available [here](https://github.com/ModusCreateOrg/ionic-vue/blob/master/cookbook/ionic-controllers.html):

- [Action Sheet](https://github.com/ionic-team/ionic/tree/master/core/src/components/action-sheet-controller)
- [Alert](https://github.com/ionic-team/ionic/tree/master/core/src/components/alert-controller)
- [Loading](https://github.com/ionic-team/ionic/tree/master/core/src/components/loading-controller)
- [Menu](https://github.com/ionic-team/ionic/tree/master/core/src/components/menu-controller)
- [Modal](https://github.com/ionic-team/ionic/tree/master/core/src/components/modal-controller)
- [Popover](https://github.com/ionic-team/ionic/tree/master/core/src/components/popover-controller)
- [Toast](https://github.com/ionic-team/ionic/tree/master/core/src/components/toast-controller)

### IonicVueRouter

`IonicVueRouter` binds Ionic transitions and routing functionalities with Vue Router.

It is an extension of the Vue Router thus it can be used as a drop-in replacement with all of the methods, hooks, etc.

### Reference App

[BEEP](https://github.com/ModusCreateOrg/beep) is a fully-featured sample application that demonstrates Ionic 4 inside a Vue.js app. Source code is available on the [GitHub repo](https://github.com/ModusCreateOrg/beep).

[BEEP](https://github.com/ModusCreateOrg/beep)

### CODE REVIEW

**Comment by jthoms1** [comment]
We discussed this in the standup this morning.  I think we are going to go ahead and merge and work on types.  This PR has no impact on the rest of ionic so I am fine with merging.

I have been assigned as a resource to get this integrated and tested.  Does that sound ok with Modus? I will probably have some changes as we continue to work through integration.

**Comment by grgur** [comment]
That sounds perfect, thank you @jthoms1. Typescript support similar to what exists for `@ionic/angular` is in the works 👍

**Comment by Cui-y** [comment]
Now that the Vue framework has been gradually supported, how can I build an app development project based on Vue ionic from scratch? 

Thank you all first.

**Comment by michaeltintiuc** [comment]
@Cui-y I'd say your best bet would be to have a look at [Beep](https://github.com/ModusCreateOrg/beep) and the [Cookbook examples from IonicVue](https://github.com/ModusCreateOrg/ionic-vue/tree/master/cookbook). I'm pointing you to @modus/ionic-vue due to the fact that @ionic/vue does not yet export the router. Other than that the above description should be enough to get anyone started. There also are [slides](https://docs.google.com/presentation/d/1VUN2C2nC2AApPDh_Jy_7MwYprWIFGI93gLvBre399l4/edit#slide=id.gc6fa3c898_0_0) from one of the meetups, perhaps those would be of some help too.

**Pull request merged**
