### PR TITLE
Fixed transition-ios animation to remove unwanted delay to click after navigation

### PR DESCRIPTION
**Pull request by RichardHoultz**
When navigating with the transition-ios the UI is not responding for a little time that makes the app fell slow. This is a proposed new setting (that can probably be improved) that removes the slow experience.

### CODE REVIEW

**Comment by Kapsul-Brice** [comment]
This needs to be merged asap since it is crucial for production apps

**Comment by arnauddrain** [comment]
Is there a reason why this has been removed from the 3.9.0? The transition are still slowing the navigation on iOS.

**Comment by radulescuandrew** [comment]
Still reproducing in 3.9.0, [this](https://stackoverflow.com/a/46509791/4423449) will fix the delay but it's not a long-term option.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
