### PR TITLE
docs(): add iOS only note to translucent props

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://github.com/ionic-team/ionic/issues/18510#issuecomment-501404919

## What is the new behavior?

- Added a note to the `translucent` props on `ion-header` and `ion-footer` that translucency only works in iOS mode.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Can we change this to say 

> Only applies to `ios` mode.

We use this verbiage in some other places.

**Comment by brandyscarney** [comment]
Also we might want to make a note it actually only applies in browsers that support backdrop-filter, so even if iOS and chrome it won't apply.

**Comment by liamdebeasi** [comment]
I can change the verbiage. I think this still applies even if backdrop-filter isn't supported, there just won't be a blur: https://codepen.io/liamdebeasi/pen/LobXZX?ionic:mode=ios

**Comment by brandyscarney** [comment]
That's odd, the code should only work if the browser supports it:

```
@supports (backdrop-filter: blur(0)) {
```

Maybe Chrome changed something recently?

**Comment by brandyscarney** [comment]
Oh you know what..apparently I only added that to Action Sheets. It _should_ be on all translucent props.

**Pull request merged**
