### PR TITLE
fix(datetime) update columns and validate value on change

### PR DESCRIPTION
**Pull request by KillerCodeMonkey**
#### Short description of what this resolves:

Dynamic datetime validation depending on current selection

#### Changes proposed in this pull request:

- Extends Picker and PickerColumn to trigger events, when the selection changes.
- Datetime listens on the new event and:
  - sets new value
  - recalculates columns
  - validates the new value

For correct Month days validation checkout #17558

**Ionic Version**:
4.0.2

**Fixes**: many of #16630

### CODE REVIEW

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi here is a little bit help needed. There is the problem that after validation render is not triggered again. So the calculation works and columns are created and disabled and the validated dateTime ist used, but you need to do a haptic change so the correct day column gets selected.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi yeah here i need a little bit help from you.

i select the correct nearest date and it is correct in the datetime component, but the change of the selected columns in the picker is not updating correctly. And i do not know why?

Maybe you can help here a little bit.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i think i can get it!... one last thing :)

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi after a long time hacking around. i am at a point where is only one little thing left.

Know everything is updated correctly, but i call `this.refresh()` after a picker column changes.

But i have to call this in a timeout so everything works like in the `componentDidLoad` hook.
So you see the `31th` day of a month dislocated for 250ms.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi so i knocked it down to simply have a timeout of 0, but there is a little flickering left.
but maybe this is enough in the first step to get the datetime picker work like you would expect it.
I am open for hints how to refresh the the cols without a timeout.

**Comment by liamdebeasi** [comment]
Ok great. Yeah apart from that flickering, everything looks good. Ideally we shouldn't have that flickering. I'll try to jump into the code and see if I can make any suggestions.

**Comment by KillerCodeMonkey** [comment]
Problem ist Here that the pickercolumn uses CSS translates to positioning
the items. If one or More items are added i wanted to Reuse the default
picker column to avoid changing the whole pickercolumn class :).

I thought of Something like set visibility to Hidden and after the refresh
timeout Set them visible.

Liam DeBeasi <notifications@github.com> schrieb am Do., 28. Feb. 2019,
15:49:

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi but maybe we can merge this back, so the datetime component is usable and works like expected. This would make many people happy. After that we can tackle the part, how to append new column options without that little flickering?

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i know why there is that flickering or not rendering when we remove the timeout.

the update method uses the rendered button elements. So when you add a column you need to wait for it to render :S

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi its doooooone... its over.... i tried my posted solution -> cols are intialized as hidden, and get visibile after first transformation.

**Comment by liamdebeasi** [comment]
This is looking a lot better! Nice work!

The one thing I'm noticing is that inertia scrolling is no longer working as it did before. Try "flinging" one of the columns and then compare it to the one in our docs: https://ionicframework.com/docs/api/datetime

It seems like it's snapping to the next item in the column a bit too aggressively. Maybe it has something to do with this? https://github.com/ionic-team/ionic/pull/17562/files#diff-c5ad26cc3f41bcf11e1dfd40af45212fR46

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi and it is me again 🤯. so i investigated. so i trigger the pickerColumnChange event only if the element is directly clicked (velocity === 0 in the onEnd method) or not decelerating (the case when notLockedIn is false in the decelerating function).

So this avoid emitting a flood of emits and refresh calls. It only refreshs if the column is locked.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i do not want to spam you, but maybe you want to check the latest fixes :)

**Comment by KillerCodeMonkey** [comment]
Sure Thing. If you want to do it, feel free. Otherwise i will Check that
tomorrow. :)

Liam DeBeasi <notifications@github.com> schrieb am Mo., 4. März 2019, 22:16:

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi here we go again :D

**Comment by liamdebeasi** [comment]
I think we're almost there! I'm wondering if we can do anything about the scroll cancelling occurring when changing columns.

For example, if you flick a time column and then change the month, the time column abruptly snaps to the nearest values whereas previously it would continue to scroll until it "eased" to a stop.

My guess is this is happening due to the column recalculations we're doing? Is there any easy way to determine whether or not we need to recalculate a column? For example, changing the month column should have no bearing on what the hour column is doing. Let me know if you need any clarification!

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi now i merge old columns with the new generated ones, so only the columns with changes get the update.

Seems like this does not cancel the flick of a column that is not affected of the previous column change.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi maybe today is the day :D

**Comment by liamdebeasi** [comment]
Hi @KillerCodeMonkey,

Sorry for just getting to this now. It looks like something broke -- going from March --> February no longer updates the "days" column (i.e. I can still select February 31, 2019).

I did make a few updates earlier this week to how datetime values are parsed/formatted relative to the user's timezone, but not sure that would cause issues.

Can you verify on your end if things are working as you'd expect?

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i added 
`Object.assign(this.picker!.columns, columns);`

to update only changed columns to avoid that https://github.com/ionic-team/ionic/pull/17562#pullrequestreview-210370638

this seems no longer to work... -.-"

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi seems like this is not solvable that easy (because of stenciljs immutable bindings). maybe i revert my latest changes and we merge it back and work up on this?

I think this pr gives the ionic community a mostly working datetime picker?

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi wait for it^^... i had another idea. Filtering the changes i want in the pickercolumn and only triggering refreshing if something changed!

Now my head is empty. Hope this works for you.
Nice sideeffect: Columns only update, when they really change.

Space for improvement: i simply use JSON.stringify to compare old and new col value. This works, because the cols are simple and not deep nested objects.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i remove PropWillChanged in favor if watch

**Comment by liamdebeasi** [comment]
Hi @KillerCodeMonkey,

I would like to try and also close out this older datetime PR: https://github.com/ionic-team/ionic/pull/14434

As a result, I have setup a branch that has a combination of your changes and changes the other contributor made. I tested and it seems to be working well. It would be great if you could also test it and let me know if you see anything wrong.

I still need to write more automated tests, so that will have to be done before it gets merged.

Here is the branch: https://github.com/ionic-team/ionic/tree/datetime-col-change

Thanks!

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi seems to work! 👍 

If you need more info for the tests. let me know. 🙃

**Comment by liamdebeasi** [comment]
Any info you have on tests would be great! Thanks!

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i only know how you write unit tests and not checked the e2e tests, yet.
what tests do you wanna add?

But there are to things to tests:
1.   the eventlistener in the datetime component, to tests that the selected value is validated and the columns are generated, e.g. changing the month should change the days from 31 to 30 or something like that.
2.   the watcher of col in picker column which should trigger refresh only if the column data changed

**Comment by liamdebeasi** [comment]
Hi there,

This issue has been resolved by #17846. You have been added as a co-author in that commit due to your contributions here.

Thank you very much for the work you put into this PR!

**Pull request closed without merging**
