### PR TITLE
feat(all): add ability to eject from Ionic sanitizer

### PR DESCRIPTION
**Pull request by liamdebeasi**
blocks https://github.com/ionic-team/ionic-docs/pull/1329 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://github.com/ionic-team/ionic/issues/18277

## What is the new behavior?

- Added `IonicSafeString`, a class that users can provide to components that allow for custom HTML in order to selectively bypass our sanitizer.
- Added a `sanitizerEnabled` config that can be used to disable/enable our sanitizer across a user's whole application.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Usage

Usage on a per-instance basis:

**Angular:**
```typescript
import { IonicSafeString } from '@ionic/angular';

...

async openAlert() {
  const alert = await this.alertController.create({
      header: 'Alert',
      subHeader: 'Subtitle',
      message: new IonicSafeString('<img src="x" onerror="alert("Hello!");">'),
      buttons: ['OK']
});

    await alert.present();
  }
```

**React:**
```typescript
import { IonicSafeString } from '@ionic/react';

...

const Home: React.FC = () => {
  const [showAlert1, setShowAlert1] = useState(false);
  
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Blank</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <IonButton onClick={() => setShowAlert1(true)} expand="block">Show Alert 1</IonButton>
        <IonAlert
          isOpen={showAlert1}
          onDidDismiss={() => setShowAlert1(false)}
          header={'Alert'}
          subHeader={'Subtitle'}
          message={new IonicSafeString('<img src="x" onerror="alert(document.cookie);">')}
          buttons={['OK']}
        />
      </IonContent>
    </IonPage>
  );
};
```

Disabling sanitizing across your entire app:

**Angular**
`app.module.ts`
```typescript
...
IonicModule.forRoot({
  sanitizerEnabled: false
})
...
```

**React**
`App.tsx`
```typescript
import { setupConfig } from '@ionic/react';

setupConfig({
  sanitizerEnabled: false
});
```

### CODE REVIEW

**Comment by brandyscarney** [comment]
Should we add this to the usage, with a big warning of "use at your own risk" or something?

**Comment by liamdebeasi** [comment]
@brandyscarney Already done 😄 https://github.com/ionic-team/ionic-docs/pull/1329/files#diff-60c4bff304f79b94d8c9721d80cec9a4R65

**Comment by brandyscarney** [comment]
@liamdebeasi Ahh always ahead of me. Ok I'll review that next!

**Comment by abuassar** [comment]
I'm just curious why it is not called IonSafeString like the rest of Ionic API?

**Pull request merged**
