### PR TITLE
Add lifecycle hooks interfaces like in angular core

### PR DESCRIPTION
**Pull request by wbhob**
#### Short description of what this resolves:
Adds support for lifecycle hook interfaces, just like Angular. By adding `implements ViewDidLoad`, classes can have access to the lifecycle hooks.

#### Changes proposed in this pull request:

- add lifecycle hook interfaces
-
-

**Ionic Version**: 3.x

**Fixes**: #7512

### CODE REVIEW

**Comment by AmitMY** [comment]
Sort of a duplicate of https://github.com/ionic-team/ionic/pull/10649, however it is a PR so who cares :)
You can cross validate that PR to yours to see if you missed anything, and @manucorporat can you review? this has been needed for a long long time :)

**Comment by manucorporat** [comment]
I think the biggest problem is how do we present this documentation in the website:
Both this PR and https://github.com/ionic-team/ionic/pull/10649/files seems correct, but it needs additional work (probably by @mhartington).

**Comment by wbhob** [comment]
Maybe they can be hidden from the docs sidemenu, and just add the interfaces to the table on the NavController page.

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com
Twitter/Instagram/Facebook: @getcanal

**Comment by wbhob** [comment]
The problem I noticed with #10649 is that each hook interface is prefixed with `On`, when the helping verbs in the hooks are `Did`, `Will`, and `Can`, so you end up with some mismatch

**Comment by wbhob** [comment]
Is this still relevant? I know Ionic 4 is coming out soon so this PR may no longer be needed.

**Comment by t-ricci-molecle** [comment]
Any update on this?

**Comment by mhartington** [comment]
Closing as this will no longer be needed with V4. Thanks!

**Comment by tylerc** [comment]
@mhartington why is this no longer needed with v4? It looks to me like lifecycle events are still a thing in v4 and they still don't have interfaces (I searched the docs and this github repo and could not find the requisite interfaces) - Am I just missing them somehow? Or is there some alternate way of handling the lifecycle that we're supposed to be using?

**Comment by mhartington** [comment]
@tylerc this was no longer needed as the PR was for v3 of ionic.

**Comment by tylerc** [comment]
For anyone from the future like me who got confused by the maze of issues and PRs, it looks like the relevant issue and pull request is now https://github.com/ionic-team/ionic/issues/18043 and https://github.com/ionic-team/ionic/pull/18044

**Pull request closed without merging**
