### PR TITLE
fix(datetime) Reloads the locale (dayName, monthName) when the picker gets regenerated to accomodate translation

### LINKED ISSUE #20367: bug: month name array cannot be changed after ion-datetime created
# Bug Report

**Ionic version:**
4.11.10

**Current behavior:**
After component init, change of month name does not reflect in the date picker

**Expected behavior:**
when date picker is being opened, month name is the newest value from input  

**Steps to reproduce:**
Change monthNames after page loaded and open date picker again to see if monthNames changed

**Related code:**
https://stackblitz.com/edit/ionic-v4-datetime-monthname

**Other information:**
This is an issue across ionic 2/3/4.
In ionic 3, my workaround is to force user to reenter the page with date picker again when language changed.
In ionic 4, from https://github.com/ionic-team/ionic/blob/master/core/src/components/datetime/datetime.tsx,
```
line 162: @Prop() monthNames?: string[] | string;
line 168: @Prop() monthShortNames?: string[] | string;
```
<del>my wide guess is without ```@Prop({ mutable: true })```, the new value does not reflect in the picker.
And</del> 
**Cause:** 
```this.locale.[monthNames/monthShortNames/dayNames/dayShortNames] ``` updated by ```convertToArrayOfStrings()``` is only loaded once in ```componentWillLoad()```
<del>One solution may be ```convertToArrayOfStrings()``` on the fly when ```open()``` called</del>
__________________________________________________________________
<del>if i misunderstand the ```mutable``` in stencil and the value is actually updated in ```ion-datetime```,</del>
just copy line 241-247 to ```generatePickerOptions()```
p.s. small performance defect applying the change

To ionic ion-datetime development member:
this is question raised in ionic 2/3 and the logic remains,
hope to see member to add some inputs here,
maybe explaining why not apply simple fix on it

### PR DESCRIPTION
**Pull request by antoinecfmws**
- Issue is:
* Currently when a language change occurs, the locale of ion-datetime is not reloaded, hence the months get only loaded once at ComponentWillLoad(), and never again. This causes a bug when the language changes and the component is re-used, i.e. ComponentWillLoad() is not triggered again.
Should close #20367 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: Similar to #20367 

## What is the new behavior?

- When the picker columns get regenerated, the local is updates from the monthNames and dayNames etc

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by antoinecfmws** [comment]
@brandyscarney sorry to tag you in this, I just wasn't sure if I am missing a step from my end to get PR approval, or if there's anything else I missed. Thank you!!

**Comment by brandyscarney** [comment]
Hey @antoinecfmws! Thanks for the PR. This looks great to me. 🙂  I tagged Liam for a review in case he has any feedback.

**Comment by antoinecfmws** [comment]
Thank you @brandyscarney !

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Comment by antoinecfmws** [comment]
Thank you!

**Pull request merged**
