### PR TITLE
fix(virtualScroll): update to Renderer2 since Renderer is deprecated

### PR DESCRIPTION
**Pull request by mnewmedia**
#### Short description of what this resolves:
Update to Renderer2 since Renderer is deprecated.

**Ionic Version**:  3.x

### CODE REVIEW

**Comment by AmitMY** [comment]
Looks like a good start.
However, PRs should be complete - it should be updated system wide. Also, in the `spec` files, there is a `mockRenderer`, that should be updated to `mockRenderer2` when it changes system wide.

**Comment by mnewmedia** [comment]
@AmitMY You are right, if I find some time I will try to do it.

**Comment by AmitMY** [comment]
@mnewmedia btw you can test the app by running `gulp validate`, to make sure you didn't break anything, as this can be a big change system wide

**Comment by mnewmedia** [comment]
@AmitMY Did a big part now, no more TS errors from my IDE. But `gulp validate` gives `Fatal undefined`. I will look deeper into this on sunday..

**Comment by mnewmedia** [comment]
Closing in favor of a PR #12147 which updated everything to renderer2

**Pull request closed without merging**
