### PR TITLE
Add single slot content projection to nav component

### PR DESCRIPTION
**Pull request by lujakob**
#### Short description of what this resolves:
Enable content projection for nav component to enable "global" elements/components on the root-page level. This feature enables having a component/element within the nav-component (that contains the root page component) and keep it across different pages. It can be controlled (disabled/enabled) from the app.component.

#### Changes proposed in this pull request:
- Add <ng-content> directive to the nav-component template.

**Ionic Version**: 2.x

**Fixes**: #10704

### CODE REVIEW

**Comment by lujakob** [comment]
@brandyscarney Is this something to be considered for a merge? It's a very important feature for our current project. Thanks.

**Comment by brandyscarney** [comment]
@adamdbradley @manucorporat Is this something we want to add? Adds ability to share components across multiple pages.

**Comment by manucorporat** [comment]
It has ability to share components that slide when the menu opens/closes. I understand the use case... but I am not sure

In theory this PR should not break anything, but adding new features always come with a cost

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
