### PR TITLE
fix(role): cancel role not close

### PR DESCRIPTION
**Pull request by rtpHarry**
I think this is correct?

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by rtpHarry** [comment]
@brandyscarney if my PR was not correct and it should be `role=close` then the documentation elsewhere needs updating, for example the 5.0 beta release notes says use buttons and `role=cancel` instead of the deprecated way.

**Comment by brandyscarney** [comment]
@rtpHarry My apologies! I think this got automatically closed when I deleted the `5.0.x` branch. This is correct, it should be `cancel` per the code & documentation here: https://github.com/ionic-team/ionic/tree/master/core/src/components/toast#usage

**Comment by brandyscarney** [comment]
Could you reopen this one on master too please and I'll get it merged?

**Comment by brandyscarney** [comment]
It won't let me reopen since the branch was deleted. 😢

**Pull request closed without merging**
