### PR TITLE
fix(router-outlet): support relative router links

### PR DESCRIPTION
**Pull request by daem0ndev**
#### Short description of what this resolves:
This PR resolves an issue where relative router links break after a forward and back navigation to a component that has already been created in the ion router outlet stack.

#### Changes proposed in this pull request:

- Create activated route proxy for each component instance activated in the outlet
- Update the underlying observables on the proxy so consumers need not be aware of implementation details

**Ionic Version**:
4.x

**Fixes**: #16534, #16736, #16954

### CODE REVIEW

**Comment by mhartington** [comment]
Merged! Thanks @daem0ndev for all your work on this and doing the investigation.

**Comment by rgolea** [comment]
What version will this launch on?

**Comment by liamdebeasi** [comment]
This will be in the next release of Ionic. I am not certain of the version yet.

**Comment by rgolea** [comment]
Great! Some minor breaking changes I've got as I just tested it, is that if you were using something like the example below, you will get `route.params` as undefined and it will get instanciated afterwards. You will have to translate that code inside `ngOnInit` (no biggie, just to write it down in breaking changes):
```
@Component({
  ....
})
export class MyComponent(){
    public id$ = this.route.params.pipe(map(params => params.id));

    constructor(
         private readonly route: ActivatedRoute
    ){}
}
```

**Comment by mhartington** [comment]
I wouldn't consider this a breaking change actually, as the example above is really an anti-pattern/not-recommended. We can make a note, but it should have been avoided to begin with.

**Comment by rgolea** [comment]
@mhartington sure! Just a note will go a long way. Thank you for the fix @daem0ndev!

**Comment by daem0ndev** [comment]
@rgolea @mhartington I created this PR to resolve the breaking change. I do agree its breaking since in a vanilla angular app, you can bind to the observables prior to ngOnInit. https://github.com/ionic-team/ionic/pull/17914

**Pull request closed without merging**
