### PR TITLE
feat(toast): expose shadow parts

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://github.com/ionic-team/ionic/issues/19722

## What is the new behavior?

- Exposed shadow parts for the container, header, message, and buttons.

Usage:

```
ion-toast::part(button) {
  background-color: "blue";
}
```

This sets the background color to all buttons to be blue.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sardapv** [comment]
this is not working i tried adding it in  global.css.. can you please give an example. I added border-top with style solid and width 50px but nothing changed.

also tried example above ion-toast::part(button) {
  background-color: "blue";
}

this is also not working.

my package.json has "@ionic/angular": "^5.0.0", i recently created new proj 10 days ago..help please @liamdebeasi

**Comment by liamdebeasi** [comment]
These PRs are just laying the groundwork for Shadow Parts. They are not part of our public API yet and may not be 100% functional at the moment . We will have an announcement/docs with usage in an upcoming release.

**Comment by sardapv** [comment]
Thank you for quick response . Appreciate it. I saw it in release notes here
https://github.com/ionic-team/ionic/releases/tag/v5.0.0
was trying to use this feature. can we expect to come this in may2020?

**Comment by liamdebeasi** [comment]
Ah yeah that should not be there. We hope to have this feature out soon.

**Comment by aparajita** [comment]
@sardapv You can easily implement this yourself until Ionic does. Call `setToastShadowParts(toast)` just before `toast.present()`:

```js
const toastShadowParts = {
  button: 'button',
  '.toast-container': 'container',
  '.toast-header': 'header',
  '.toast-message': 'message'
}

function setToastShadowParts(toast) {
  Object.entries(toastShadowParts).forEach(([selector, part]) => {
    const el = toast.shadowRoot.querySelector(selector)

    if (el) {
      el.setAttribute('part', part)
    }
  })
}
```

**Comment by Kokkinis99** [comment]
Any updates on this @liamdebeasi ?
Messing around with toasts and still can't get to style the shadow parts even with `::part()`.

package.json: `"@ionic/angular": "6.3.7"`

**Comment by liamdebeasi** [comment]
We have some Shadow Part examples here that you could follow: https://ionicframework.com/docs/api/toast#theming

Also make sure the element you are trying to style has a part exposed on it. You can tell by looking for the `part="..."` when inspecting the element.

**Pull request merged**
