### PR TITLE
fix(slides): fix panning zoomed in slide

### PR DESCRIPTION
**Pull request by themastersoda**
Fixed typo inside slides component which prevented zoomed in slides from being panned. 

**Ionic Version**: 2.x

**Fixes**: #10963

### CODE REVIEW

**Comment by quentinburley** [comment]
1)
I tested this patch also on ionic v3.0.1 and it works just as with ionic 2.x.

2)
I performed some tests with this patch on touch device (safari ipad ios10.3 in full screen).

A pure-zoom initiated by a double tap or by a pinch-out works perfectly.  OK.

The pan and zoom is OK, and certainly better than without the patch (didn't work at all before)
It may be possible, however, to improve the effect of pan when performing for example a vertical pan (drag up or down with one finger once already zoomed) in a horizontal direction <ion-slides>, it works but drags also the top/bottom bounds during the pan, and this is undesirable. A similar effect happens also for the combined pinch-zoom.

**Comment by quentinburley** [comment]
here is an issue that come up after some detailed testing of this patch on ionic v3.0.1, tested on ipad safari (ios 10.3).

With a large number of slides and `<ion-slides [zoom]="true" ...>` , its possible to crash safari just by changing slides rapidly using `this.slides.slideTo(...)` on a click event, and clicking rapidly.

This crashing does NOT occur with zoom disabled, `<ion-slides [zoom]="false" ...>`.

Of course this issue is not related to the patch in question (which just makes the existing zoom implementation able to work, thanks!), but I beleive the underlying zoom implemention hasn't been sufficiently tested.

**Comment by jayordway** [comment]
Any updates on this PR, is it going to be merged? Pan/Zoom is not working with slides currently with 3.8.0

**Comment by jurgen-reconcept** [comment]
Please merge this!

**Comment by themastersoda** [comment]
It is ridiculous how merge request that

**Comment by nurfgun** [comment]
any update on this!? please merge!

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
