### PR TITLE
feat(rtl): menu update side in runtime

### PR DESCRIPTION
**Pull request by AmitMY**
WIP

#### Short description of what this resolves:
Update menu type when platform direction changes

#### Changes proposed in this pull request:
- Move the menu-type functionality from constructor to a separate method
- Store the correct side in `_side`, don't save normalised side
- `isRightSide` is now a magic method instead of a variable (avoid mistakes when changing dir in runtime)
- Add event emitter to when direction changes, and update the type when it does

#### Explanation:
- First thing is to add support for `menuToggle` for `start` and `end` (just missing from menu in general)
- In menu types, I moved a part of the constructor to another method `updatePosition`, which sets the menu enter / close animation. (This worked when you start ltr, or start rtl, but not if you want to switch)
- I added an event emitter to platform, to know when direction changes, and when it does, I call the `updatePosition` again to set the correct animation (because `start`/`end` are now the opposite sides)
- I also changed the basic test to use `start`/`end` instead of `left` and `right`.

#### Problem:
If you switch direction, the `updatePosition` is called again, and instead of overriding the animation, it seems to clash with it, so it animates from the middle, see: https://youtu.be/3VFDO7otYrU

**Ionic Version**: 3.x

All tests passing

### CODE REVIEW

**Comment by AmitMY** [comment]
@manucorporat This one completes https://github.com/driftyco/ionic/pull/11233
Let me know what you think

**Comment by AmitMY** [comment]
@manucorporat ?

**Comment by chukwu** [comment]
Based on the youtube video linked from @AmitMY, this solves my problem.
When is this going to be shipped? What version is this expected?

**Comment by chukwu** [comment]
Everything explained by @AmitMY was what I expected.

1. An observable/Event Emitter which listens to setDir and updates dom especially when updatedocument argument  is set to true on runtime.
2. Dynamically toggle menu sides attributes from right to left and vice-versa.

Guys, I am working on multiple production projects which strongly requires this to work on runtime without manually reloading the page and managing states.

**Comment by AmitMY** [comment]
@chukwu Same as you, I am looking forward this getting merged. Unfortunetly, there is a bug here, because I don't clear the animation state before re-setting it. (so it partially works on android/windows, and does not on iOS)
I am in contact with some Ionic members to help fix that issue, and if/when that is fixed, it can be merged. However, currently there is kind of a code freeze on v3, and that is why so many PRs (~25) are not being reviewed.

**Comment by mahmoudrabie** [comment]
We need help from IONIC team to solve this problem ASAP.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
