### PR TITLE
fix(content): hide scrollbar on desktop platform when content doesn't need to scroll

### PR DESCRIPTION
**Pull request by 5im0n**
#### Short description of what this resolves:

By default content always display an horizontal scrollbar even if the content doesn't need to scroll.
This fix is mainly usefull on desktop browser

#### Changes proposed in this pull request:

- overflow-y from *scroll* to *auto*

**Ionic Version**: 2.x

**Fixes**: #
scrollbar

### CODE REVIEW

**Comment by Manduro** [comment]
There's a reason for it to be set to `scroll`, see [this issue](https://github.com/driftyco/ionic/issues/6022#issuecomment-228110736).

**Comment by 5im0n** [comment]
Alright, I had not seen this discussion.

I propose to had `overflow-y: auto` only on desktop.

```
.platform-core .content {
  overflow-y: auto
}
```

**Comment by manucorporat** [comment]
There is much better way to fix this, without changing `overflow`, going to take a look

**Comment by 5im0n** [comment]
@manucorporat Eager to see what you have in mind 😄

**Comment by laser-me** [comment]
@manucorporat Actually this is connected to another problem (https://github.com/driftyco/ionic/issues/6416). And applying 
```
.scroll-content {
  overflow-y: auto
}
```
could benefit a lot not only for desktop.

The problem is that when we have a scrollable content (ion-list) that does not require scroll the rule (overflow-y: scroll) force it to show scroll. Yet everything is fine unless you have menu with another scroll bar on the left. Toggling menu on/off reveals a small gray box just at the start of content that is not part of dom, but a artifact of scroll bar that is not needed for the content at the moment.

**Comment by mariohmol** [comment]
Hi there.. this is really useful.. when using a lot of components app looks very weird.. one thing that would be good to have is apply to tabs as well.. i guess this PR would fix for tabs as well.. right?

what i used in my app `.show-tab ng-component { overflow-y: auto; }`

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
