### PR TITLE
feat(range): detect scroll for range slider

### PR DESCRIPTION
**Pull request by frederickjansen**
#### Short description of what this resolves:
Fix problem where you can't touch a range slider and still scroll the page, without introducing config flags that disable functionality.

#### Changes proposed in this pull request:
Change range slider behavior to match Android sliders: detect the initial direction the user moves to after touching a range component. If the direction is up or down, enable scrolling. If it's left or right, activate the range component. This behavior is kept as long as their finger is held down.
To keep support for tapping on the track while showing a pin, make the pin disappear after 0.5 seconds.

**Ionic Version**: 2.x

**Fixes**: #6956

### CODE REVIEW

**Comment by biesbjerg** [comment]
Nice job!

**Comment by mohi-ir** [comment]
yes! it seems a nice solution :)

**Comment by manucorporat** [comment]
@frederickjansen have you tested this in device?
it is a very hard problem to stop scrolling once it has started. ie. calling ev.preventDefault() in touchMove does not usually work.

**Comment by frederickjansen** [comment]
We have this code running in production for ~4 months now and haven't noticed any issues. I'm still using the same e.preventDefault() code that was there previously. But now when you're actually scrolling, it ignores the inputs on the range component (with the _forceScroll property).
Unless there was a bug with e.preventDefault() that was already present in that version of the code, I don't believe this code changes that particular behavior. I haven't checked the code after RC4's major refactoring though.

**Comment by frederickjansen** [comment]
@manucorporat I made the branch compatible with Ionic v3 again. The only thing I cannot figure out is how to force a DOM update (see [line 374](https://github.com/driftyco/ionic/pull/9272/commits/c662c105c6e1777cb41ba5b9c427dea9fad6728c#diff-83239da88903453f22312d13f7b81defR374)). This is required only when the user has the pin enabled, and they tap on the range component instead of dragging it. Without the setTimeout hack, the pin won't appear.

**Comment by manucorporat** [comment]
@frederickjansen you probably need to wrap update around `zone.run()` but I am not sure that is the correct way to make it work.

Have you looked at: https://github.com/driftyco/ionic/blob/master/src/gestures/drag-gesture.ts ? 

PanGesture is used across the whole framework, it is a high quality implementation of drag gesture that used by Menu swipe, Swipe to go back, sliding item and others. I would suggest to create a new: knob-gesture class and extend from PanGesture or SlidingGesture, just like menu-gesture, or sliding-item.

I am not sure the current solution is good enough to be merged, too many things can go wrong, for example: the range and swipe to open a menu by swipping could be activated at the same time, PanGesture will handle it for you.

**Comment by frederickjansen** [comment]
@manucorporat I hadn't looked at PanGesture, but I'm not sure if I want to add that level of complication to the range slider. If it wasn't used by Ionic for that purpose before, should I really be adding it? The only change I really want to make is to ignore the range component when you're scrolling the page, as is done natively by Android and iOS.
The "side effect" my code introduces is that if you just tap the range component with pin enabled, it doesn't show the pin instead of the current behavior, which shows it for 0.1 seconds. I'm fine with that tradeoff (for now) because it fixes a much bigger usability issue.

Would you be okay accepting the PR if I just get rid of the setTimeout hack and CSS changes? This PR has been open for 6 months now, and I've had to rewrite it twice because of structural changes to the Ionic codebase. I'd prefer to get the most important piece in now so that it survives the next merge conflict, and figure out a better way to deal with the pin later.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
