### PR TITLE
fix (module-loader): remove module from ModuleLoader cache map on promise reject

### PR DESCRIPTION
**Pull request by longgt**
#### Short description of what this resolves:
Module loader is trying to cache loaded module in map.
After that, when loading page having lazy loading feature, module loader try to get from map instead of loading new for performance reason.
But when module loader failed to loaded lazy chunk (network probs..etc), it should try it again instead of get from map.
On promise reject call back of module loader, remove module from cache.

**Ionic Version**: 3.x

**Fixes**: #13639

### CODE REVIEW

**Comment by codinronan** [comment]
I'd like to see if this can get merged, my metrics show this is happening to every 1 out of 20-30 users which is ALOT more than I would have expected. I'm honestly shocked it can happen at all, network is not necessary to load these chunks since they are already on the device right? So I'm not sure what the root cause is, but I'd like to see if this can help reduce the frequency.

**Comment by longgt** [comment]
Ionic Team announced that they are focusing on v4 and there is no any more update will be released on v3.
If you need this pull, fork and merge by yourself instead.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Comment by longgt** [comment]
@BAWES 

You can get it from https://github.com/longgt/ionic, longgt/iss13639 branch.

**Pull request closed without merging**
