### PR TITLE
fix(datetime): support min/max for 12-hour clock

### PR DESCRIPTION
**Pull request by flivni**
#### Short description of what this resolves:
Fixes: Setting min/max on datetime component does not work with 12-hour clock; am/pm column.

There were a few ways to implement. I took the path that would have the least impact to the existing code. Let me know your thoughts as to the approach.

#### Changes proposed in this pull request:

- 12-hour clock now starts with 12 and ends with 11, e.g. 12am, 1am, 2am, ... 11am
- am/pm is added to dateSortValue(..)

**Ionic Version**: 2.2

**Fixes**: #10797

### CODE REVIEW

**Comment by flivni** [comment]
Hi @manucorporat. Can you take a look? Thanks.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Comment by Camisado** [comment]
Hey guys
I'm using ionic-angular@3.9.2 and do not see this fix there.
Is it possible to add these updates to ionic-angular@3.9.2 ?
Thank you in advance.

**Comment by BibekBharatiDas** [comment]
Hey team. I am using Ionic 5. I am still facing this issue. Please help.
My code is :-

`<ion-datetime displayFormat="DD/MM/YYYY HH:mm" displayFormat="DD/MM/YYYY h:mm A" formControlName="startDateTime" [min]="minDate" autocomplete="off"></ion-datetime>`

`this.minDate = moment().format("YYYY-MM-DDTHH:mm:ss")`

datetimepicker

**Pull request closed without merging**
