### PR TITLE
Fix(forms): set disabled attribute

### PR DESCRIPTION
**Pull request by loopezz**
#### Short description of what this resolves:
Disableing a FormGroup or FormControl doesn't update the input fields with a disabled attribute immediately. This attribute will be added after that specific input field **has and loses focus**. However, after re-enableing the FormGroup or FormControl the disabled attribute doesn't get removed.

#### Changes proposed in this pull request:
Sets the proper disabled state on the first child (input element) of nativeElement if possible. This will update the HTML input correctly:
- Adds/removes disabled attribute on HTML input

**Ionic Version**: 3.9.x

**Fixes**:
#12359
#13170

### CODE REVIEW

**Comment by patrickmcd** [comment]
Does it fix https://github.com/ionic-team/ionic/issues/12904 as well?

**Comment by loopezz** [comment]
Yes, clicking the disable toggle buttons in the e2e test are looking good. However, I'm not sure if this is the right way to fix it. We'll see! 👍

**Comment by husainsr** [comment]
I had Fixed it using dom in ts file.


`let field = document.getElementById("tag");
    let children = field.getElementsByTagName("input");
     for(var i=0;i<children.length;i++)
     {
      children[i].removeAttribute("disabled");
     }
`

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
