### PR TITLE
fix(virtual-scroll) Allow conditional rendering for virtual scroll

### PR DESCRIPTION
**Pull request by HugoHeneault**
#### Short description of what this resolves:
When VirtualScroll is conditionally rendered after view init, it's stuck in "virtual-loading" state.

#### Changes proposed in this pull request:

This might not may the most elegant way of doing it, but it seems to fix a long-standing issue. If anyone has a cleaner way, just tell me and I'll do it, or open your own PR and I'll close this one. 🙂 

- Add `isReadReady` and `isWriteReady` properties to the `viewController`, allowing devs to access theses properties after `readReady` and `writeReady` events have been emitted
- When `VirtualScroll` is being constructed, if read and write is ready, render the virtualScroll because the events won't be emitted as they have already been.

**Ionic Version**:  3.9.x

**Fixes**: 
- #7734
- #9655
- #7198

If you want to use it in your project I made an ionic build : https://github.com/ionic-team/ionic/pull/13406#issuecomment-352393445

### CODE REVIEW

**Comment by HugoHeneault** [comment]
@masimplo Feel free to tell what you think of this one :)

**Comment by ghenry22** [comment]
@manucorporat any chance this could get rolled into the next 3.x release?

**Comment by tahasabih** [comment]
Can we get this merged please?

**Comment by HugoHeneault** [comment]
Hey guys. If anyone is needing it, here's an archive on ionic-angular you can use as a workaround. It's ionic-angular 3.9.2 + the vs fixes : [ionic-angular-3.9.2-conditional-vs.tar.gz](https://github.com/ionic-team/ionic/files/1567590/ionic-angular-3.9.2.tar.gz)

**Comment by HugoHeneault** [comment]
I updated my build with some weird edge case fix. See previous message.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
