### PR TITLE
fix(header): fix collapsing iOS header when using with split pane

### PR DESCRIPTION
**Pull request by liamdebeasi**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: https://github.com/ionic-team/ionic/issues/19541

## What is the new behavior?

1. Check the correct bounding box in the IO handler
2. Account for any left/right offsets when doing nav transitions

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
Released dev build for this `4.11.0-dev.201910021714.944a660` cc @mhartington

**Comment by brandyscarney** [comment]
I'm still seeing this 🤔

**Comment by liamdebeasi** [comment]
@brandyscarney Are you testing the dev build above? I'm testing it on your conference app changes and everything looks like it's working fine

**Comment by brandyscarney** [comment]
Okay perfect, testing the right issue out and this is fixed! :tada:

**Pull request merged**
