### PR TITLE
refactor(error-handler): remove use of deprecated param

### PR DESCRIPTION
**Pull request by AmitMY**
#### Changes proposed in this pull request:

- remove use of deprecated parameter
- remove explicit super constructor call

**Ionic Version**: 3.x

### CODE REVIEW

**Comment by AmitMY** [comment]
Hi @jgw96 
Removing the super call has nothing to do with that line.
Here is an example you can run in console:
```
class ErrorHandler {
	constructor() {}
	handleError(err) {alert(err)}
}

class IonicErrorHandler extends ErrorHandler {
	handleError(err) { super.handleError(err) }
}

new IonicErrorHandler().handleError("hey");
```

The super is implicitly called.

**Comment by jgw96** [comment]
Hmmm very true. Does this PR work locally for you? I pulled, built and then tested this in an app and was getting `Can't resolve all parameters for IonicErrorHandler: (?).`

**Comment by AmitMY** [comment]
Hmm strange.. 
I did mainly the same thing (copied IonicErrorHandler, created a local IonicErrorHandler2) and passed it, and it worked.
Do you have `"emitDecoratorMetadata": true` in your tsconfig perhaps? (answers online say it might be the cause - http://stackoverflow.com/questions/42022843/error-cant-resolve-all-parameters-for-e)

**Comment by jgw96** [comment]
So yeah all Ionic apps created with our cli have that config https://github.com/driftyco/ionic2-app-base/blob/master/tsconfig.json#L5. This is definitely strange. Doing some searching to see what might be going on here.

**Comment by AmitMY** [comment]
@jgw96 I am not sure how you get this error.. (or how you test this specifically)
If you add `@Injectable` decorator (because it is a provider), does it help?

**Comment by AmitMY** [comment]
@jgw96 How did you test? `e2e.watch` or `validate` or something else?

**Comment by jgw96** [comment]
@AmitMY I will give this one another look soon. When I was testing I was doing a full build of the framework using `gulp release.prepareReleasePackage` and then copying over `dist/ionic-angular` to `node_modules/ionic-angular` in the conference app.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
