### PR TITLE
feature(v3): update @angular v6.1.1

### PR DESCRIPTION
**Pull request by rdlabo**
#### Short description of what this resolves:

Update dependencies package. We still need Ionic v3. and if update ionic v3 to v4, I think we should update angular package first.
So I want to update Ionic v3 to correspond Angular 6(This is LTS!）.

#### Changes proposed in this pull request:

update @angular package.
update rxjs6
update @ionic-native

**Ionic Version**: 3.x

### CODE REVIEW

**Comment by rdlabo** [comment]
update @angular v6.1.1 and remove rxjs-compat. I rebase and re-make pull request.

**Comment by mohamedsharaf** [comment]
@brandyscarney @manucorporat 

really this request is great can we get it for ionic 3 please review and merge

**Comment by rdlabo** [comment]
I want `Ionic v3 to correspond Angular 6` package is npm publish as `next` version by ionic team. 

- This help users keep using v3.
- This help update v3 to v4(isolate problems when errors occur).

ex:
```
"ionic-angular": "next",
```

**Comment by mhartington** [comment]
Hi there! We're going to be closing this as the repo is now organized for V4. For V3 related issues/PRs, please direct them here 

https://github.com/ionic-team/ionic-v3

Thanks!

**Comment by rdlabo** [comment]
Sure. I will create https://github.com/ionic-team/ionic-v3/pull/812 .

**Pull request closed without merging**
