### PR TITLE
Updating Modal component - Angular usage code

### LINKED ISSUE #17976: v4 Docs: Modal Angular usage + typo
On the v4 [Modal component page](https://ionicframework.com/docs/api/modal), "paramaters" is spelled wrong and the Angular Usage example is missing the import of "Input" from Angular Core:

import { Component } from '@angular/core';
should be
import { Component, Input } from '@angular/core';

because of:
// "value" passed in componentProps
@Input() value: number;

### PR DESCRIPTION
**Pull request by dotNetkow**
#### Short description of what this resolves:
Fixes #17976 

#### Changes proposed in this pull request:
- Fix typos
- Update Angular usage

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hey there! Can you run `npm run build` from the root directory?

**Comment by brandyscarney** [comment]
Actually a build won't fix it. The second change needs to be made in this file @dotNetkow: https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/usage/angular.md

And then running `npm run build` will automatically update the README to reflect. 🙂 

https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#modifying-documentation

**Comment by dotNetkow** [comment]
@brandyscarney and @liamdebeasi all set 👍 thank you both!

**Comment by brandyscarney** [comment]
Merged! I linked it to the docs issue in the commit here: b081ca4dd09116909ccab625f10fa00fe73efda1

**Pull request merged**
