### PR TITLE
feat(transition): iOS page transition shadow

### PR DESCRIPTION
**Pull request by adamdbradley**
>EXPERIMENTAL: Adds a page shadow to transitioning pages on iOS. Disabled by default.

To enable, set the `experimentalTransitionShadow` Ionic config to `true`

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Performance is great on my iPhone 5s!

Noticing one thing: The shadow seems to be bigger relative to native. Here are some comparisons:

*iPhone 7 (iOS 13)*

| Ionic  | Native |
| ------------- | ------------- |
| IMG_5951| IMG_5952 |

* iPhone 5s (iOS 12.2)*

**Comment by liamdebeasi** [comment]
Performance is great on my iPhone 5s!

Noticing one thing: The shadow seems to be bigger relative to native. Here are some comparisons:

*iPhone 7 (iOS 13)*

| Ionic  | Native |
| ------------- | ------------- |
| IMG_5951| IMG_5952 |

*iPhone 5s (iOS 12.2)*

| Ionic  | Native |
| ------------- | ------------- |
| IMG_0016| IMG_0018 |

**Comment by liamdebeasi** [comment]
Updated comparison:

*iPhone 5s (iOS 12)*

| Ionic  | Native |
| ------------- | ------------- |
| 5s-ionic-ios12|5s-native-ios12|

*iPhone 7 (iOS 13)*

| Ionic  | Native |
| ------------- | ------------- |
| 7-ionic-ios13|7-native-ios13|

*iPhone Xs Max (iOS 13)*

| Ionic  | Native |
| ------------- | ------------- |
| xs-max-ionic-ios13|xs-max-native-ios13|

**Comment by RafaelKr** [comment]
Hey, this looks great!
I would like to learn if there is a specific reason that you used a background-image for .transition-shadow and not a box-shadow. Is this more performant?

**Comment by RafaelKr** [comment]
> I would like to learn if there is a specific reason that you used a background-image for .transition-shadow and not a box-shadow. Is this more performant?

@adamdbradley this would be really interesting to me, thank you :slightly_smiling_face:

**Pull request merged**
