### PR TITLE
feat(rtl): add transform and transform-origin support for rtl

### PR DESCRIPTION
**Pull request by AmitMY**
#### Short description of what this resolves:
bad support on rtl for transform and transform origin

#### Changes proposed in this pull request:

- add mixins to control transform and transform origin

Preview: http://ionic-snapshot-go.appspot.com/ionic2/snapshots/hhp/x9v/chrome_400x800

**Ionic Version**: 3.x

### CODE REVIEW

**Comment by AmitMY** [comment]
@brandyscarney Please label as `rtl`

**Comment by Khalid-Nowaf** [comment]
Hi @AmitMy, I just would like to ask if this PR related to animations when the DOM is RTL, because I noticed some wired movments in real device when the keyboard slides up and moves an INPUT and a Labels  DOM, the lable blink "not visible for while" while the input cursor moves in wired way .   Thanks

**Comment by AmitMY** [comment]
@Khalid-Nowaf It relates to a very limited amount of animations. More animations are controlled from TS, and I did not address those here.

I am not sure about what you are seeing, but if you create an issue with a video and/or a reproduction repo, We could have a look

**Comment by Khalid-Nowaf** [comment]
@AmitMY, I just create an Issue #11745, and there is a video and reproduction repo.

**Comment by brandyscarney** [comment]
Refactored the transform mixin so that it can be used like:

```
@include transform(translate3d(5px, 0, 0), scale(0.5), rotate(5deg));
```

on this commit: https://github.com/ionic-team/ionic/commit/dab832bd4549196b9cd0b4dd4e3c8b8d0a46ea50

**Comment by brandyscarney** [comment]
:tada:

**Pull request merged**
