### PR TITLE
Default ion-datetime picker to current date if bound value is not set

### PR DESCRIPTION
**Pull request by jarrodkoch**
#### Short description of what this resolves:

Use current date to initialize the ion-datetime picker if the ion-datetime has no value.
#### Changes proposed in this pull request:
- When opening the ion-datetime picker, check to see if there is a current value.  If there is not a current value, use the current date and time to initialize the picker columns.  Otherwise, continue existing behavior.

**Ionic Version**: 2.x

**Fixes**: I do not believe there is an open issue regarding this.  There are some questions about this functionality in the forums, though.  One such is https://forum.ionicframework.com/t/datetime-default-to-todays-date/53178

### CODE REVIEW

**Comment by manucorporat** [comment]
@jarrodkoch thanks for the PR. can you squash all your commits?
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

Then rename the final commit to:
```
feat(datepicker): using current date when no value is provided
```
or something like that...

then force push the changes into the same branch, so the PR is updated.

**Comment by jarrodkoch** [comment]
I'll work on getting the commits squashed...will I need to remove this pull request and submit a new one, or is this something that can be done within the scope of this pull request?

**Comment by jarrodkoch** [comment]
Hopefully this is what you wanted...is there anything else I need to do?

**Comment by manucorporat** [comment]
mmm, looks like the number of commits is still 12 haha, it should be just 1
(just  `feat (datepicker) Use current date and time to initialize picker col...` )

Not sure what you did, you should squash all your commits into a single one, since you are in fact changing the historial, you will need to call: `git push origin --force`

**Comment by jarrodkoch** [comment]
I squished the squish and forced push to origin, hopefully it's squared away now.

**Comment by jgw96** [comment]
Hello @jarrodkoch , would you be able to fix the merge conflicts on this PR please so we can continue to review? Thanks!

**Comment by shyamal890** [comment]
+1 Waiting for this feature

**Comment by RichardM99** [comment]
+1 Has this feature been implemented?

**Comment by shaarawy130** [comment]
Does this work yet?? doesn't seem to be working for me

**Comment by demonzoo** [comment]
Will this be released soon in version 3.0.x? This is very important for us as well!

**Comment by eddyng8** [comment]
+1 Please implement this feature as soon as possible. This issue preventing me from moving to ionic 3. In Ionic 2.1.1, I used the hack described by mkuklis [here](https://forum.ionicframework.com/t/datetime-default-to-todays-date/53178/7). However, this hack no longer work in Ionic 3. The ion-datetime will display the today's date when the hack is applied. In ionic 2.1.1 it worked perfectly because the ion-datetime stayed blank but it picked today's date when the picker is opened.

**Comment by brandyscarney** [comment]
I'm going to close this as there are unresolved merge conflicts. If there is an open issue for this please link it to me or we can open a new one to track this. Thanks!

**Comment by Bishoy** [comment]
has this feature been implemented yet ?

**Comment by demonzoo** [comment]
For those who are expecting this feature/fix, please try the native date picker plugin. It will work as expected.

**Comment by RichardM99** [comment]
@demonzoo

What about on desktop?

**Comment by eddyng8** [comment]
In order to get around this bug, I created a custom component that uses native date picker in ios and android and fallback to ion-datetime in the browser. I won't take all the credit. Somebody posted somewhere on how to do this (for some reason, I could not find that post anymore. So, whoever did it, thank you very much). I just adjusted it a little so that it fulfills what I need for my project. Feel free to copy and paste and adjust to what you need. As a bonus, I added the clear button in ios and android so that I can clear the value of my date picker. The input and output is a string in this format: 2099-12-31T00:00Z.

Without further ado, here are the steps:

1. Install ionic's native date picker plugin as described here: https://ionicframework.com/docs/native/date-picker/

2. Added native-date-picker.component.html into src/shared folder (feel free to move it to another folder in your project).

```
<ion-item no-lines>
    <ion-label stacked>{{label}} <span *ngIf="required">*</span></ion-label>
    
    <ion-datetime displayFormat="MMMM DD YYYY" *ngIf="pickerType=='core'" [disabled]="isDisabled" [max]="max" [min]="min" [ngModel]="isoValue" (ngModelChange)="updateDate($event)" [class.error]="control != null && !control.valid && control.touched"></ion-datetime>

    <ion-input [readonly]="isInputReadOnly" (click)="dateInputManagement()" [disabled]="isDisabled" [ngModel]="shortDateValue" *ngIf="pickerType=='android' || pickerType=='ios'" [class.error]="control != null && !control.valid && control.touched"></ion-input>

    <ion-icon item-right name="close" (click)="clearDate()" *ngIf="pickerType=='android' || pickerType=='ios'"></ion-icon>
</ion-item>

```

3. Added native-date-picker.component.ts into the same folder.

```
import { Component, Input, Output, forwardRef, EventEmitter } from '@angular/core';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';

import { Platform } from 'ionic-angular';
import { DatePicker } from '@ionic-native/date-picker';

import moment from 'moment';

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => NativeDatePicker),
    multi: true
};

@Component({
    selector: 'native-date-picker',
    templateUrl: 'native-date-picker.component.html',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]

})
export class NativeDatePicker implements ControlValueAccessor {

    //The internal data model
    public shortDateValue: any;
    public isoValue: string;

    public pickerType = null;    
    public displayFormatForIonDateTime: string = "MMMM DD YYYY";

    public isInputReadOnly: boolean = true;

    @Input() isDisabled;
    @Input() label;
    @Input() required;
    @Input() control;
    @Input() max = '2099-12-31T00:00Z';
    @Input() min = '1900-01-01T00:00Z';
    @Output() onChange: EventEmitter<any> = new EventEmitter();
    
    //Set touched on ionChange
    onTouched() { 
        if (this.control != null) {
            this.control._touched = true;
        }
    }

    //From ControlValueAccessor interface
    writeValue(value: any) {        
        if (value !== undefined && value !== null) {
            this.isoValue = value            
            this.shortDateValue = (moment.utc(value)).format(this.displayFormatForIonDateTime);
        }
        else {
            this.isoValue = this.shortDateValue = '';
        }
    }    

    updateDate(event: any) {
        this.onTouched();
        this.onChange.emit(event);
    }

    clearDate() {
        this.writeValue(null);
        this.onTouched();
        this.onChange.emit('');
    }

    //From ControlValueAccessor interface
    registerOnChange(fn: any) {
        this.onChange.subscribe(fn);
    }

    //From ControlValueAccessor interface
    registerOnTouched(fn: any) { //leave it empty
    }
    
    constructor(public platform: Platform, private datePicker: DatePicker) {
        if (this.platform.is('android')) {
            this.pickerType = "android";
        } else if (this.platform.is('ios')) {
            this.pickerType = "ios";
        } else if (this.platform.is('core')) {
            this.pickerType = "core";
        }
    }
    
    public dateInputManagement = () => {
        if (!this.isDisabled) {
            let dt: any = this.isoValue != null && this.isoValue.length > 0 ? new Date(parseInt(this.isoValue.substr(0, 4)), parseInt(this.isoValue.substr(5, 2)) - 1, parseInt(this.isoValue.substr(8, 2))) : new Date();
            let dtMax: any = null;
            let dtMin: any = null;

            if (this.max != null && this.max.length > 0) {
                if (this.pickerType == "ios") {
                    dtMax = new Date(parseInt(this.max.substr(0, 4)), parseInt(this.max.substr(5, 2)) - 1, parseInt(this.max.substr(8, 2)));  // ios takes datetime
                }
                else {
                    dtMax = new Date(parseInt(this.max.substr(0, 4)), parseInt(this.max.substr(5, 2)) - 1, parseInt(this.max.substr(8, 2))).getTime();  // android takes milliseconds
                }
            }

            if (this.min != null && this.min.length > 0) {
                if (this.pickerType == "ios") {
                    dtMin = new Date(parseInt(this.min.substr(0, 4)), parseInt(this.min.substr(5, 2)) - 1, parseInt(this.min.substr(8, 2)));  // ios takes datetime
                }
                else {
                    dtMin = new Date(parseInt(this.min.substr(0, 4)), parseInt(this.min.substr(5, 2)) - 1, parseInt(this.min.substr(8, 2))).getTime();  // android takes milliseconds
                }
            }

            let options = {
                date: dt,
                mode: 'date',
                maxDate: dtMax,
                minDate: dtMin,
                androidTheme: this.datePicker.ANDROID_THEMES.THEME_DEVICE_DEFAULT_DARK
            };

            this.datePicker.show(options).then(
                (date) => {
                    var strDt = moment(date).format('YYYY-MM-DD') + 'T00:00Z';
                    this.writeValue(strDt);
                    this.updateDate(strDt);
                }).catch((error) => {
                });
        }
    }

}
```
4. In app.module.ts, add the following:

```
import {NativeDatePicker} from '../shared/native-date-picker.component';

@NgModule({
  declarations: [
    MyApp,
    ...
    NativeDatePicker,
    ...
  ],
  entryComponents: [
    MyApp,
    ...
    NativeDatePicker,
    ...
  ]
  })

```
5. When you want to use it:
In your html:

```
<native-date-picker formControlName="ISOBirthday" [label]="'Birthday'" [required]="true" [max]="'2019-12-31T00:00Z'" [control]="crewForm.get('ISOBirthday')"></native-date-picker>
```

In your *.ts:

```
this.myForm = new FormGroup({
    ISOBirthday: new FormControl(this.ISOBirthday, Validators.required)
});

```

**Pull request closed without merging**
