### PR TITLE
fix(sliding-item): ionSwipe event is fired

### LINKED ISSUE #12146: ionSwipe event not being called when ion-item-options has content
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Tested in 3.4.2 and 3.4.0 with below code 

```
<ion-list>
  <ion-item-sliding #slidingItem>
    <ion-item>
      Item
    </ion-item>
    <ion-item-options (ionSwipe)="share(slidingItem)">
      <button ion-button (click)="share(slidingItem)">Share</button>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>
```

With above code ionSwipe event is not being triggered

Same thing if I remove the content inside `ion-item-options` i.e as shown below, then ionSwipe event is triggered

```
<ion-list>
  <ion-item-sliding #slidingItem>
    <ion-item>
      Item
    </ion-item>
    <ion-item-options (ionSwipe)="share(slidingItem)">
    </ion-item-options>
  </ion-item-sliding>
</ion-list>
```
Plunker for 3.4.2 -> Feature Completely broke i.e doesn't work no matter how far you swipe -https://embed.plnkr.co/iVh1yXdwA0l7PC3n4S8T/

Plunker for 3.4.0 -> Feature works  -> http://embed.plnkr.co/puyuJKjb1CATwTdtpsIV/

**Expected behavior:**
ionSwipe event should be fired  with or without content inside `ion-item-options`

**Steps to reproduce:**
Please refer to the plunker above

I didn't verify this but my guess would be its broke with this commit -> https://github.com/ionic-team/ionic/commit/61935602a19bd49833ada7ca1f6b684cf690c1df#diff-de4ce1132acfce42a66591355b348b31

### PR DESCRIPTION
**Pull request by manucorporat**
fixes #12146

### CODE REVIEW

**Comment by codebeauty** [comment]
Cool, any idea of time for the next tagged release? 

Keep it up 👍

**Comment by codebeauty** [comment]
@patrickmcd What have I missed, why thumbs down? It is just a important question for me.

**Comment by patrickmcd** [comment]
@codebeauty Your comment is inconsiderate spam to this repo's ~2000 watchers. It adds nothing to the conversation. It is just another "plus one / are we there yet" comment which only serves to fill our inboxes.

We all have "important questions" and features we want implemented. If each of us made similar comments, this forum would be useless and our inboxes would be full.

Additionally, and ironically, comments like yours **slow down development**. The time the Ionic team wastes reading and responding, is time they could spend writing code.

Exercising patience, rather than nagging the Ionic team, will speed up delivery of new features and is more considerate to watchers.

**Comment by codebeauty** [comment]
@patrickmcd nagging the team or spam is not my intention. Bugfixes of common features like this one are really important. I unfortunately forgot the watchers, sorry for that. Will not happen again. 
 
But just placing a negative emoji not really helps the communication in any way. Sorry for circumstances and I'll wait.

Thanks, and again keep up the good work. 
Bye 
Mathias

**Pull request merged**
