### PR TITLE
fix(Datetime): correct days in month calculation

### PR DESCRIPTION
**Pull request by KillerCodeMonkey**
#### Short description of what this resolves:

Calculates the correct intial days in a month
Keep in mind this does not solve the issue, that valid dates are not recalculated after a month/year change (#17562)

#### Changes proposed in this pull request:

- use native javascript to get days in month instead of custom leap year and day calculation

**Ionic Version**:
4.0.2

**Fixes**:
an issue as part of #16630: #17510 #16733

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening a PR! Would you be able to add a few tests to verify this fix? You can add them to the `datetime.spec.ts` file in `src/components/datetime/test/`. Thanks!

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi sure thing :)

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi here it comes. some simply tests for the months of this year and february of the next leap year

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi is there any internal agenda when you will merge these datetime prs? it is a little bit hard to keep them up to date and keep on track for external contributors 😉

**Comment by liamdebeasi** [comment]
Hi @KillerCodeMonkey,

I plan on merging this along with your other PR since it seems like the other PR is a pre-requisite. I will look at your other PR today.

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi nice to hear that. let me know if you need something.

**Comment by liamdebeasi** [comment]
Hey there,

Is this PR still needed now that the other datetime PR has been merged in?

Thanks!

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi you can decide. this is using native JS Dates to get days in month and does not need a leapyear check :) or ifs if a month has 30 or 31 days.

**Comment by liamdebeasi** [comment]
Ok cool! Does it fix any particular bug, or is it just more of a style thing?

**Comment by KillerCodeMonkey** [comment]
more of a style thing :)

**Comment by liamdebeasi** [comment]
Ok make sense! What if we revert the changes to `daysInMonth`, but kept the tests? I'm not sure we need to change the `daysInMonth` functionality if it's already working. We can always use more tests though 🙂

**Comment by KillerCodeMonkey** [comment]
Feel free to only use the tests 😋

**Comment by liamdebeasi** [comment]
Thank you! 🎉

**Pull request merged**
