### PR TITLE
feat(select): Allow select options in popover to be individually styl…

### PR DESCRIPTION
**Pull request by audaxion**
…eable.

#### Short description of what this resolves:
Allows individual select options in a select popover to be styled separately.

#### Changes proposed in this pull request:

- Add cssClass to SelectPopoverOption and apply it to ion-label in the popover.

**Ionic Version**: 4.0.0

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! This looks great, but would it possible to instead grab the class and pass it? Like the following:

```
<ion-select-option class="my-class">red</ion-select-option>
```

I'll have to look into this more but wanted to comment first. 🙂

**Comment by audaxion** [comment]
I like that suggestion. I've updated the PR to use class instead of the new property cssClass.

**Comment by audaxion** [comment]
I'd love to get some movement on this. My app depends on this feature and I've had to run with a custom build for quite a while now as a result. Any chance of an update?

**Comment by brandyscarney** [comment]
@audaxion Unfortunately there were console errors when I tried running this last time and I haven't had time to look into why. If you'd like to try running it locally to see what is happening we have some steps here: https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#core

**Comment by audaxion** [comment]
@brandyscarney Thanks for the feedback. I found and fixed what was causing the console errors and I added to one of the tests to show what my change does.

**Comment by brandyscarney** [comment]
I'm sorry it's taken so long for me to get back to this. I went ahead and implemented it on a new PR instead of trying to fix the conflicts with master: https://github.com/ionic-team/ionic/pull/21304

I added you as a co-author though so you still get the contribution: https://github.com/ionic-team/ionic/commit/5285824da5258ea638420fc60c50e0a19952f89c

This will go into our `5.2` release. Thank you for your work on this! 🙂

**Pull request closed without merging**
