### PR TITLE
[Toast] Improvements for ToastCmp

### PR DESCRIPTION
**Pull request by mfdeveloper**
#### Short description of what this resolves:

Changes to improve `ToastController` usage and fixes some issues related on this repo.

If this changes here it's ok, I will create a issue on  https://github.com/ionic-team/ionic-site repo with these new options for update the documentation.

#### Changes proposed in this pull request:

- Optionally pass HTML content into `Toast` message. Use option `messageHtml` for this
- Optional `closeClick` event to call when the close button is clicked. 
- Use `color`option to pass a color for close button, like described in: [Snackbars & toasts](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs) specification.
- New option `autoFocus` to avoid loses focus of input fields, when a `toast` is presented.
- 🆕 Fixed **double click** on dismiss button error `Uncaught (in promise): removeView was not found` (2017-11-27)

**Ionic Version**: 2.x / 3.x

**Fixes**: #12106 #11309 #11692

### CODE REVIEW

**Comment by alan-agius4** [comment]
Cool stuff, would love you see the option to set a 'color' to the toast, similar to other components

**Comment by JasonZzs** [comment]
Hey,I want to use this,But I can't get it when i download code from git.

**Comment by mfdeveloper** [comment]
Hello @JasonZzs !! This changes aren't still on **[master]** branch. So, you need clone my fork https://github.com/mfdeveloper/ionic and clone or download zip. 

After @brandyscarney or any contributor of IONIC accept this PR, you will can get here this code :smile:

**Comment by JasonZzs** [comment]
@mfdeveloper  Thank you very much.I will download your code and this may help me a lot  ;  so  so  so   much thanks for your suggest;

**Comment by mfdeveloper** [comment]
Yeah @mburger81, I'm agree with you. Your suggestions have concerns with material design [Snackbars & toasts ](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) specifications.

**Comment by mburger81** [comment]
Perhaps in 3.9.0? 😀

**Comment by brandyscarney** [comment]
Thanks for the PR! 

@manucorporat what do you think of these changes?
@kensodemann could we get this in for a review soon?

**Comment by Infinite-Studio** [comment]
Hello,
A planned date for the integration of this PR ?

Thx.

**Comment by mfdeveloper** [comment]
Added a extra minor fix:

- 🆕 Fixed **double click** on dismiss button error `Uncaught (in promise): removeView was not found`

**Comment by tgensol** [comment]
@mfdeveloper I was looking for this error for so long ! I will try your fix

**Comment by salbahra** [comment]
The focus being stolen from input is a problem for us and seeing as how this PR has solved it, I would love to know if there is any chance this will be merged in?

Thanks!

**Comment by mburger81** [comment]
Hi, I'm pretty sure the team will not merge any PR for components any more!  Probably you have to merge your PR to the core branch and migrating all your changes to the new implementation.

@kensodemann can you have a look on this PR?

**Comment by kensodemann** [comment]
@mburger81 - you are correct. There are no plans for another v3.x release so any existing PR will most likely need to be refactored for v4 after it is out.

**Comment by mfdeveloper** [comment]
@salbahra as @kensodemann and @mburger81 said, the changes made here will not be merged with **[master]**, until the `4.0` stable version will released. So, whether you wish this changes of this PR by now, you can follow one of the strategies below:

- Change the source of the dependency `ionic-angular` for my fork in your `package.json` file:

```json
 "dependencies": {
    ...
   "ionic-angular": "mfdeveloper/ionic#toast-improvements"
 }
```

- Create custom classes for `ToastCmp`, `Toast` and `ToastController` with the changes here. 

> If the PR [!12601](https://github.com/ionic-team/ionic/pull/12601) were merged, you need override only the `ToastCmp`, and pass your new custom component for `ToastController` core class. I'm so sorry about this 😢   

- Create a custom "subpackage" (e.g using [lerna](https://github.com/lerna/lerna) ) into your project folder structure, with the changes of this PR, with the `ionic-angular` **3.x** version like dependency.

I hope that suggestions help you!! I'm sorry about this 😞

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
