### PR TITLE
feat(searchbar): autofocus directive (desktop only)

### PR DESCRIPTION
**Pull request by manucorporat**
(last commit only)
DO NOT MERGE UNTIL THIS PR ( https://github.com/driftyco/ionic/pull/8162 ) IS MERGED!!

**Fixes (partially)**: https://github.com/driftyco/ionic/issues/5834

### CODE REVIEW

**Comment by Manduro** [comment]
@manucorporat Would be really nice to have this!

I've done some research on this some time ago and have been using a directive which so far seems to work great on mobile (cordova only) as well. It does require the `<preference name="KeyboardDisplayRequiresUserAction" value="false" />` preference in `config.xml`.

Another thing I've learned is that autofocus is terrible on cordova when the input that gets focus is still being animated. That's why I'm using the `ngAfterViewInit` lifecycle event with a relatively long timeout, so I'm sure all view animations are finished. I see you are using the `viewController.didEnter` which should be even better!

This directive works on all elements/components that have an `<input>` inside, like `<ion-input>` and the searchbar as well. It would be great to see autofocus support for additional components integrated into Ionic as well :).

```ts
import { AfterViewInit, Directive, ElementRef, Renderer } from '@angular/core';

@Directive({
  selector : '[customAutofocus]'
})
export class AutofocusDirective implements AfterViewInit {
  constructor(
    private renderer: Renderer,
    private elementRef: ElementRef
  ) {}

  ngAfterViewInit() {
    const element = this.elementRef.nativeElement.querySelector('input');
    setTimeout(() => {
      this.renderer.invokeElementMethod(element, 'focus', []);
    }, 800);
  }
}
```

**Comment by Manduro** [comment]
@manucorporat I found out that my autofocus only works in UIWebView. (related: https://github.com/driftyco/cordova-plugin-wkwebview-engine/pull/22)

**Comment by Lightheaded** [comment]
Can't wait for this! Without this the UX is just plain broken

**Comment by Lightheaded** [comment]
Any estimation on when/if this would be merged?

**Comment by karlpatrickespiritu** [comment]
Would be great if this will be released soon :)

**Comment by AmitMY** [comment]
@manucorporat Just noting that PR #8162 was merged, so what is blocking this PR?

**Comment by brandyscarney** [comment]
@manucorporat Can you fix the merge conflicts on this and if it is still correct we can get it merged?

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
