### PR TITLE
(feat): define top-level ARIA landmark regions to improve accessibility

### PR DESCRIPTION
**Pull request by amymarsh4work**
Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

**Comments**
- I can contribute to the docs under your direction. Since I'm not making API changes, it may not be needed
- I'm very curious about how to approach creating an automated test in this scenario. I ran the tests but did no modifications.

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
Assistive technologies are unaware of important top-level structural elements of the page, such as: header (banner), content (main), and footer (contentinfo). Without this context, it's very challenging to understand the overall, high-level structure of the application.

Issue Number: [18671](https://github.com/ionic-team/ionic/issues/18671)

## What is the new behavior?
This feature aims at giving all perceivable content on a page a semantically meaningful role - focusing on the top-level of the Accessibility Tree. Assigning each region a role would make it easy for assistive technology users to understand the meaning of the overall layout of a page, content and functionality it contains.

## Does this introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
These changes are to enhance support for assistive technologies. They are not intended to change the visual appearance of the UI.

This was helpful to validate and test in Chrome:
https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#pane

### CODE REVIEW

**Comment by amymarsh4work** [comment]
@brandyscarney Hi Brandy! I racking my brain on how the CI build failed on the angular-e2e-test step. It's complaining about providers and all I changed was a tiny bit of html in ionic/core. My master branch  compares exactly to Ionic's master. Another contributor appears to be having trouble getting a PR to build too. Please advise. :) 

**************************************************
*                    Failures                    *
**************************************************

1) providers should load all providers
  - Expected '' to equal 'true'.

2) providers should detect testing mode
  - Expected '' to equal 'true'.

Executed 42 of 42 specs (2 FAILED) in 1 min 1 sec.
[05:19:34] I/launcher - 0 instance(s) of WebDriver still running
[05:19:34] I/launcher - chrome #01 failed 2 test(s)
[05:19:34] I/launcher - overall: 2 failed spec(s)
[05:19:34] E/launcher - Process exited with error code 1
An unexpected error occurred: undefined

**Comment by brandyscarney** [comment]
Hey @amymarsh4work! Thank you for the PR! Unfortunately we have some race conditions causing the Angular tests to fail on PRs randomly that we need to fix, but I have initiated a re-build to see if we can get the test passing. 🙂

**Comment by brandyscarney** [comment]
Thank you for another PR! We really appreciate the accessibility help. 🙂

**Comment by amymarsh4work** [comment]
@brandyscarney Thanks Brandy! Accessibility is also very important to us here at U of M! 

BTW - Looks like the e2e workflow step might have hit a speed bump again. :)

**Comment by brandyscarney** [comment]
@amymarsh4work Yeah fixing up our e2e testing is on our list. 🙁 There are some timing issues that are only happening on CI and not locally.

**Comment by amymarsh4work** [comment]
@brandyscarney Hi Brandy! I've been keeping an eye on this and it looks to me that even though you approved my PR and merged it to master, it never actually made it into 4.7.0 or 4.7.1. I guess this is because the e2e test CI step failed? Is there anything that can be done to get this into a release? 

Here's a StackBlitz with Ionic 4.7.1 installed where I'm seeing one of my changes missing. The div inside of ion-content shadow-root should actually be a main HTML 5 tag. 
https://stackblitz.com/edit/ionic-v4-angular-tabs-4-7-1

BTW - I'm really, really happy you guys got StackBlitz to work! It did take some wrangling though - I ended up having to downgrade core-js to version 2.6.9 in order for it to work. :)

**Comment by brandyscarney** [comment]
@amymarsh4work Hey! So sometimes the release branch is created prior to a merge making it in `master`. That is what happened here so it didn't make it into the `4.7.0` release. The `4.7.1` release was only made to fix a regression that slipped in for `4.7.0` so it was forked directly from the `4.7.0` code base, not `master`. Our release schedule is every 2 weeks on a Wednesday, so if it didn't make it in the last release it will be in the one next Wednesday, Aug 7. 

I created a dev release off master if you want to use it now: `@ionic/angular@4.8.0-dev.201907311738.32bb1f7`

**Comment by brandyscarney** [comment]
Here is the release branch / PR where you can see which commits made it in: https://github.com/ionic-team/ionic/pull/18885/commits

**Comment by amymarsh4work** [comment]
Oh, good! It all makes sense now. Thanks for getting back with me and for the dev release! That really helps us. :)

**Pull request merged**
