### PR TITLE
feat(toast): swap string interpolation to `innerHTML` to display content

### PR DESCRIPTION
**Pull request by cesareian**
#### Short description of what this resolves:
This will resolve that the consumer can pass plain text, URLs and/or image links and they will show correctly in the toast component

#### Changes proposed in this pull request:

- swap string interpolation to `innerHTML`

**Ionic Version**: 2.x & 3.x

**Fixes**: #12106

### CODE REVIEW

**Comment by mfdeveloper** [comment]
Hey guys @cesareian and @Remco75 I did more things to fix this on PR #12515. Please, check this :)

**Comment by JasonZzs** [comment]
how could I pass a html element?

**Comment by alan-agius4** [comment]
@mikehamil10 any feedback re this please?

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Comment by mfdeveloper** [comment]
@codewise-nicolas Sadly, ionic team don't merge any PR's to `v3`, and the `v4` is a completly new structure. I don't using this new version yet...I'm waiting release a stable version to verify the new code and maybe, re-submit the closed PR's.

Organizations that using `v3` by now, needs a time to migrate for any new version. I'm feel like that "waste my time" when theses PR's were closed arbitrarily

**Comment by codewise-nicolas** [comment]
I agree completely. Many people are still on v3.
This request seems like such basic functionality.

Ive gone ahead and modified the module locally to make the change to innerhtml.

**Pull request closed without merging**
