### PR TITLE
docs(): add config docs

### PR DESCRIPTION
**Pull request by mhartington**
#### Short description of what this resolves:
Add docs for config options and method

### CODE REVIEW

**Comment by brandyscarney** [comment]
@manucorporat Is this good to merge?

**Comment by manucorporat** [comment]
I think this should be include in ionic-docs repo, stencil will not pick up this docs since there is not a real component behind it

**Comment by brandyscarney** [comment]
@camwiegert thoughts?

**Comment by mhartington** [comment]
If thats the case, the platform docs can also be moved there as well.

**Comment by camwiegert** [comment]
Yeah this could live in the docs. Should it live in the API reference?

**Comment by brandyscarney** [comment]
Going to close this in favor of putting it in the `ionic-docs` repo, thanks Mike! https://github.com/ionic-team/ionic-docs/issues/270

**Pull request closed without merging**
