### PR TITLE
fix(largeTitle): fix background transparent at title.

### PR DESCRIPTION
**Pull request by rdlabo**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type
Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
If `color` set or set darkmode in  using Collapsible Large Titles, ion-title's background is be transparent. 

スクリーンショット 2019-10-21 23 52 30

And test code was not compliant with the Documentation.

## What is the new behavior?

- ion-title's background is be default color. 
- test code is be compliant with the Documentation.

スクリーンショット 2019-10-21 23 49 50

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- I changed using `border-style` instead of opacity

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This fix would actually break the existing large title functionality. The toolbar border and background color should fade in/out as the user scrolls (easiest way to see this on a native iOS app is in the Settings app). I'm not sure this particular change is the correct solution, but I definitely agree that this is something to figure out.

I'm going to discuss with the team and hopefully will come back with a few other ideas soon. Thanks! 🙂

**Comment by rdlabo** [comment]
@liamdebeasi  Thanks for review.I should have tmp animation gif.
This is animation gif for my changes. 
https://gyazo.com/be50c329c7de80ed7d59ddbd298926ab

This may not break the existing large title functionality. Thanks.

**Comment by liamdebeasi** [comment]
Yeah it's a really subtle detail that Apple added in iOS 13 😅 

Here is the behavior on `master`: https://giphy.com/gifs/dUB0wznnkjoiaKuap7
Here is the behavior on your branch: https://giphy.com/gifs/j6ASaa6C9BIkwcYIjV

Notice that on your branch the border below the main header doesn't show up until it's completely collapsed.

**Comment by rdlabo** [comment]
Oh, I see. You are right. Sorry!! 

First I tried to use `--ion-border-color-rgb` for `border-color: rgba(var(--ion-border-color-rgb), 0)` . But not defined, and occere break changes. So I change to use `border-style` .
Perhaps `--ion-border-color-rgb` was better.

Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the PR! We appreciate all the hard work you did to create this.

After discussing with the team, we have decided to make it a requirement that `fullscreen="true"` be set on `ion-content` and `translucent="true"` be set on `ion-header` in order to have the collapsible large title functionality work. We looked at what native iOS apps do, and basically all of the apps that use the collapsible large title also have translucency enabled.

The need for this stems from the fact that the content background color needs to "peek through" the main header when the large title is not collapsed. This required us to change the opacity on the main header toolbars background. On apps that use things like dark mode, this caused a white space up top since the main header did not overlay the `ion-content`.

I am going to close this PR in favor of https://github.com/ionic-team/ionic/pull/19956 where I have made a note of this as well as updated usage examples. Thank you!

**Pull request closed without merging**
