### PR TITLE
feat(item-divider): add inner padding CSS variables

### LINKED ISSUE #18484: bug: ion-item-divider (iOS) has no "--padding-inline-end" variable
# Bug Report

**Ionic version:**
**4.4.2**

**Current behavior:**
For element `<ion-item-divider>` when I set `--padding-inline-end: 0;` in the styles it doesn't not work for iOS because no variable exists for the _padding-inline-end_ that now has 8px hard coded (no issues for Android):

image

**Expected behavior:**
Please make _padding-inline-end_ a variable: `--padding-inline-end`

### PR DESCRIPTION
**Pull request by corollari**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: fixes #18484

## What is the new behavior?

It solves: #18484

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

All credit goes to @brandyscarney, I just implemented the solution she proposed on #18484

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hey there,

Just wanted to mention a couple things before we merge:

1. Since these are new CSS variables, we need to document them (This will make this PR a feature instead of a bug fix).
2. The variables need to be initialized before we can use them. You can just initialize them to 0.

Can you make these changes? I can take another look after. Thanks!

**Comment by corollari** [comment]
Sure, but how do you want me to document these variables? In your contributions guide you state that documentation should go in the component's readme.md but (apart from the huge auto-generated blob which mustn't be modified) there's no variables documented there.

**Comment by corollari** [comment]
@liamdebeasi Just applied the changes you requested. Not sure if I should document the variables in a different way, right now it feels very copy-pasty.

**Comment by brandyscarney** [comment]
Thank you @corollari! I added a few small changes. I'll let Liam take another look, but looks good to me! 🙂

**Comment by corollari** [comment]
@brandyscarney cool, it seems I forgot to build the documentation.
Also, given that this is now a new feature, should I change the commit messages? or is that not needed because of the pre-merge squash?

**Comment by brandyscarney** [comment]
@corollari It's not needed, we'll update it on squash & merge. Thank you though!

**Comment by brandyscarney** [comment]
Thanks again! 🙂

**Comment by corollari** [comment]
Kudos for the awesome handling of this PR :smile:

**Pull request merged**
