### PR TITLE
fix(reorder-group): should be able to reorder items from within a sha…

### PR DESCRIPTION
**Pull request by adamlacombe**
#### Changes proposed in this pull request:

- reorder-group: createGesture on `this.el` instead of `this.doc.body`

**Ionic Version**: 4.1.1

**Fixes**: #17746

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the PR! Would you be able to add some tests that verify this functionality? Thanks!

**Comment by adamlacombe** [comment]
Sure, I'll give it a shot. I just added a standard interactive test. I'll add onto that to verify this functionality shortly.

**Comment by adamlacombe** [comment]
@liamdebeasi All set - let me know if you have any questions or concerns. Thanks!

**Comment by brandyscarney** [comment]
Thanks for the PR! The fix looks good to me. 🙂 @liamdebeasi Could you review the tests?

**Comment by liamdebeasi** [comment]
Hey there,

I pushed a few updates to your branch regarding the tests:

- simplified the tests a little bit and reorganized some functions
- sped up the tests (originally they were running at ~2600ms on my machine, got them down to ~700ms)

Going to do another quick look over, but everything else looks really great! Nice work! 🎉

**Comment by brandyscarney** [comment]
Merged :tada:

**Pull request merged**
