### PR TITLE
fix(picker): pick closest option at low velocity

### PR DESCRIPTION
**Pull request by greimela**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #19659 

## What is the new behavior?

Select the closest picker option when releasing the picker column at rest.

This makes it easier to pick a specific option since it is closer to the behavior of the native iOS picker.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by Maikell84** [comment]
Thank you, Looks very good.
Can you please Merge this asap? We strongly need this fix.

**Comment by robingenz** [comment]
That's exactly what I need.
Can you merge this asap?

**Comment by havok1983** [comment]
go for it

**Comment by Maikell84** [comment]
Any news? Why is this not merged yet?
Any comments from the ionic team?

**Comment by greimela** [comment]
Hi @liamdebeasi, is there anything missing that prevents this change from getting merged?
Seems like some people are waiting for this fix.

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Pull request merged**
