### PR TITLE
feat(split-pane): expose max/min-width css variables of side-panel

### PR DESCRIPTION
**Pull request by troyanskiy**
#### Short description of what this resolves:

Exposes `min-width` and `max-width` of the side panel

#### Changes proposed in this pull request:

- expose `min-width` with `--side-min-width` css variable
- expose `max-width` with `--side-max-width` css variable

**Ionic Version**: 4

**Fixes**: #17088 

Note: Initially I named the variable with `--min-width` and `--max-width`, but somehow they were overwritten by `:host` of the inner menu.

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! So in order for the split pane to work with CSS variables in IE it will need to be converted into either a shadow or scoped component.

Example shadow component; menu: https://github.com/ionic-team/ionic/blob/master/core/src/components/menu/menu.tsx#L13

Example scoped component; card: https://github.com/ionic-team/ionic/blob/master/core/src/components/card/card.tsx#L12

- Components using (reading) CSS variables, need to be scoped or shadow
- Components using <slot> should be shadow

I think if we could make it into a shadow component that would be best, but if not it needs to be changed to be scoped at a minimum. Please let me know if this is something you want to tackle!

I believe @camwiegert took a look at this previously.

**Comment by zardilior** [comment]
Please include this PR!!

**Comment by tgangso** [comment]
Any progress?

**Comment by brandyscarney** [comment]
In order for the CSS variables to work properly the component had to be converted to scoped/shadow. Liam has added a PR to convert split pane to shadow here: https://github.com/ionic-team/ionic/pull/19754

We will make sure to add @troyanskiy as a co-author to that PR. 🙂

**Pull request closed without merging**
