### PR TITLE
 fix(item): handle multiple inputs inside ion-item correctly

### LINKED ISSUE #15850: bug: multiple inputs inside of an ion-item (ion-checkbox, ion-radio, ion-toggle, ion-datetime) combine click events
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.2.0 (/Users/robinhinderiks/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/robinhinderiks/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/robinhinderiks/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
Lets say i have a checkbox and a ion-datetime in the same ion-item. I can not select the checkbox but instead will select the ion-datetime. This also happens when you have multiple ion-datetime's for example time selection from - to it will always select the last ion-datetime even if you click on the first one

**Steps to Reproduce**
1. Use the code below anywhere in your app. 
2. Try to select the checkbox.

**Related Code**
`
<ion-item >
            <ion-checkbox slot="start" [(ngModel)]="block.selected"></ion-checkbox>
            <ion-datetime placeholder="startTime" [ngModel]="block.startTimeTest" display-format="HH:mm"></ion-datetime>
</ion-item>
`
**Expected Behavior**
Be able to use both elements

### PR DESCRIPTION
**Pull request by DavidStrausz**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
Issue number: fixes #15850 

## What is the new behavior?

- Items with multiple clickable inputs position slotted (slot=end) inputs relatively
- Items with inputs (checkbox, toggle, ...) and clickables (ion-button, a) add a z-index of 3 for the clickable elements

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by DavidStrausz** [comment]
@brandyscarney Could you please either merge this or close it, otherwise I'm not able to submit another pull-request :)

**Comment by brandyscarney** [comment]
@DavidStrausz Sure! There are conflicts with master, did you want me to close it to re-open it with conflicts resolved?

**Comment by DavidStrausz** [comment]
@brandyscarney I could rebase on master in my repo and resolve the conflicts if you're still planning on merging this, but as its been sitting around since may I would have submitted a PR for something else now as the user-land workaround for this works well for us :)

**Comment by lppedd** [comment]
@DavidStrausz thanks for the effort, even if we can't appreciate it in production yet.

**Comment by brandyscarney** [comment]
@DavidStrausz I haven't had time to review the UX portion of this. There were some changes I made awhile back to fix some of the problems with item's clickable elements related to disabled inputs: https://github.com/ionic-team/ionic/blob/1a8b7a4559860b3efa4778a78c905e30f18587bf/core/src/components/item/item.tsx#L130-L142

Here's the commit: https://github.com/ionic-team/ionic/commit/dfa2b13c3a408c6288acc38ce5de480ff04c88fc

I created a Codepen of some of the scenarios listed to see what was still not working and it seems like buttons are the only remaining issue where it isn't working entirely: https://codepen.io/brandyscarney/pen/wvvxjXE?editors=1100

I think it may just need CSS updates for the slots in order to fix the covers, but I need to review the native UX for it.

**Comment by DavidStrausz** [comment]
@brandyscarney I resolved the conflicts and added a fix which also accounts for the remaining issue with ion-button.

**Comment by brandyscarney** [comment]
This is great! Thank you so much for making the updates, adding tests, and being patient with us. I pushed a few small changes, mostly adding the `ion-anchor` and `button` elements to look for as clickables. 

I added a small change to account for the problem @lppedd is experiencing with setting the item itself to clickable when there is a input cover, but I think that issue itself is outside of the scope of this problem (will comment on the original issue with more steps). 

Once the build passes this is ready to go. Thanks again!

**Comment by DavidStrausz** [comment]
No problem, always glad go help out and improve the framework!

Nice thinking with the additional clickables, I wasn‘t sure how many to add, most probably it will be necessary to add some more over time when people want to place some other elements there.

**Comment by brandyscarney** [comment]
I published a dev build for this if anyone wants to try it out: `5.0.0-dev.201911132228.c139c9a`

It's based on master which includes some Ionic 5 changes since we aren't doing new development on Ionic 4 at the moment. Changes for Ionic 5 can be seen here: https://github.com/ionic-team/ionic/releases/tag/v5.0.0-beta.0

**Pull request merged**
