### PR TITLE
fix(infinite-scroll): properly updates scrollTop of ion-content

### PR DESCRIPTION
**Pull request by stalniy**
#### Changes proposed in this pull request:

- add class property `_prevDim` which stores dimensions at time of firing `ionInfinite` event
- add fix for iOS motion and `scrollTop` conflict, just disable and reenable motion after some time

**Ionic Version**:  3.x

**Fixes**: #11587

### CODE REVIEW

**Comment by stalniy** [comment]
As a temporary solution, I just copy pasted `InfiniteScroll` class in my project with such configuration:
```js
import { InfiniteScroll as IonicInfiniteScroll } from 'ionic-angular'

@Directive({
  selector: 'my-infinite-scroll',
  providers: [
    { provide: IonicInfiniteScroll, useExisting: forwardRef(() => InfiniteScroll) }
  ]
})
export class InfiniteScroll {
```

**Comment by tobiasmuecksch** [comment]
@brandyscarney Any ETA when this will be integrated to ionic?

**Comment by tobiasmuecksch** [comment]
@stalniy I've tried to use your InfiniteScroll class in my project, but it didn't work for me. This is what I did:

1. Create a file called `my-infininite-scroll.ts`
2. Copy your changed file
3. Correct the import paths
4. Change the directive settings like you mentioned above
5. use `<my-infinite-scroll>`instead of `<ion-infinite-scroll>`

On iOS the lazy loading stopped working completely without any error.
Could you please provide the file you've added to your project? Maybe I did something wrong somewhere...

Ionic 3.6.1
WKWebView

**Comment by stalniy** [comment]
@tobiasmuecksch here is the snippet https://gist.github.com/stalniy/bea9a080387ddaef65d6e04628f744cb Don't forget to import module with your custom infinite scroll

**Comment by zjcjoaquin** [comment]
@stalniy I 've tried your snippet and it works most of time.
but sometimes the infinite-scroll would scrollTo the new data 's scrollTop and it would back to the right scrollTop position after a little ms.
this seems your new infinite-scroll could not prevent the scroll-content 's default motion sometimes

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
