### PR TITLE
perf(button-effect): remove button-effect from DOM

### PR DESCRIPTION
**Pull request by manucorporat**
DO NOT MERGE

### CODE REVIEW

**Comment by lweb20** [comment]
@manucorporat please close this pull request if you don't want merge this.

**Comment by danielsogl** [comment]
@lweb20 you know that he and I are ionic team member? ^^ you don't have to comment like this

**Comment by lweb20** [comment]
IMHO If not expect comments, these should not be enabled.

Pd:
Do not misunderstand my words, they are translated xD

**Comment by manucorporat** [comment]
@danielsogl  what happened?

**Comment by danielsogl** [comment]
@manucorporat He wrote you shouldn't create PR's if you don't merge them :D Nothing offensive

**Comment by manucorporat** [comment]
@danielsogl hahaha funny, well, most of the DONT MERGE mean:

1. higher priority issues appear, and the PR is not finished
2. Needs a meeting in order to 

We have this policy in other for other member of the team, to

**Comment by manucorporat** [comment]
@danielsogl @lweb20 hahah no worries, I was just curious :D
Sometimes they are non-trivial PRs that require a lot of time, creating a PR is good way to great to get feedback from other members of the team or the community itself.

Sometimes, it is just not the right time to merge it, since it does not match with the mid-term roadmap or there are higher priority issues, but creating a PR is a good way to don't forget it, this PR is a good example.

**Comment by lweb20** [comment]
@manucorporat I made a comment about the commit but @danielsogl not expected the strange comment. I'm new in this and I don't know who are Ionic-team members.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
