### PR TITLE
feat(checkbox): implement indeterminate state

### PR DESCRIPTION
**Pull request by simonhaenisch**
#### Short description of what this resolves:

Implements an indeterminate state for checkboxes.

#### Changes proposed in this pull request:

This adds an `indeterminate` prop to the `ion-checkbox` component, which visually renders the checkbox with a dash to indicate an indeterminate state.

| MD | iOS |
|-|-|
| indeterminate-checkbox-md | indeterminate-checkbox-ios |

For MD styles I followed [Material specs](https://material.io/design/components/selection-controls.html#checkboxes) (see section "Parent and child checkboxes") and the [Material Components for Web implementation](https://material-components.github.io/material-components-web-catalog/#/component/checkbox) to implement the dash according to the specs. For iOS styles I had a look at https://github.com/Marxon13/M13Checkbox.

Should I add an E2E test for the most common use case of it, which is a nested tree of checkboxes? That's why I'm submitting this anyway, because we need it for our work.

One change I am not totally sure about is that I had to remove `position: static` for checkboxes within items. Not sure why it was there in the first place because it seems to work fine with `position: relative`, however I assume there was a reason for this?

**Ionic Version**: `4.0.0-rc.0`

**Closes**: #16943

### CODE REVIEW

**Comment by simonhaenisch** [comment]
@brandyscarney could you have a look at this please? We want to use this in our app and would prefer `ion-checkbox` supporting this rather than having to create our own checkbox component.

I can work on getting this PR ready if any changes are required.

**Comment by brandyscarney** [comment]
Thanks for the PR! I plan to review this soon. Sorry for the delay. 🙂

**Comment by liamdebeasi** [comment]
Also, we are planning on removing the `preview` folders, so would you be able to add your tests to the `basic` test? Thank you! 🙂

**Comment by simonhaenisch** [comment]
ok will do that later... the screenshots were taken in chrome though, so not sure why it wouldn’t work there? anyway i’ll make sure it’ll work in safari and firefox as well.

**Comment by brandyscarney** [comment]
This is such a great PR! Nice work. I am going to take a look at this now and make some changes to the tests. Just letting you know so we don't do twice the work. 🙂

**Comment by brandyscarney** [comment]
I was actually seeing the same thing as Liam in Chrome, so I modified it to use an svg like the checkmark icon which eliminates a lot of the CSS. This _may_ have broken some of the functionality, I am still looking into it and going to work on adding the parent/children test case next.

screen shot 2019-02-28 at 12 59 31 pm

**Comment by brandyscarney** [comment]
I made some changes to the CSS to add back some things that were removed. I believe `position: static` was added so that checkbox wouldn't have problems if it were in an item with a toggle or something similar, but I can't recall the exact reason.

I added a native indeterminate checkbox example to the test here: `http://localhost:3333/src/components/checkbox/test/indeterminate`

This shows that our determinate checkboxes are behaving the same as native. I also added a parent/child example and it seems to be working as expected. 

Please let me know if you're seeing any problems with my changes, otherwise it should be good to go. Thank you!!

**Comment by simonhaenisch** [comment]
Yup looks great, thanks for your work!

**Comment by brandyscarney** [comment]
Thank you :tada:

**Pull request merged**
