### PR TITLE
feat(card): add button

### PR DESCRIPTION
**Pull request by jlbeard84**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
A feature has been requested to introduce button click behavior to cards whereas this did not exist prior.

Issue Number: #17773 

## What is the new behavior?
- Cards can now accept attributes much like ion-item to allow them to operate as buttons with the appropriate styling.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by brandyscarney** [comment]
This is great! I added some small tweaks to the CSS for iOS, but this is good to merge when the build is done. Thank you!! :tada:

**Comment by tmk1991** [comment]
Love the feature! It needs a tweak - not sure if I should open a bug for it? 

The new button isn't inheriting the card styling. Had to apply: 
```
ion-card {
    button {
       height: 100%;
       border-radius: inherit;
       background: transparent !important;
    }
}
```

**Comment by brandyscarney** [comment]
@tmk1991 Yes could you please open a bug report with a way to reproduce 🙂

**Comment by Rubenima** [comment]
Could we have some code that shows the new features of the ion-card? It will be very nice, as i am searching for a solution that incorporates it.

Thank u 🙂

**Comment by brandyscarney** [comment]
@Rubenima The card got a few additional properties: 'button', 'type', 'disabled', 'href', and 'routerDirection`. If it has a `button` or `href` property it will render as a button or anchor, based on which property is used. Here's a code example in vanilla JS:

```
<ion-card button onClick="clicked()">
  ...
</ion-card>
```

**Comment by Rubenima** [comment]
Thank u so much! 😃 I'll be waiting for the implementation of the example posted on twitter, it looked AMAIZING! 👍

**Pull request merged**
