### PR TITLE
fix(slides): add effect plugins for swiper

### PR DESCRIPTION
**Pull request by CFT-Chris**
#### Short description of what this resolves:
Missing Coverflow, Cube, Fade and Flip swiper effects for ``ion-slides``

#### Changes proposed in this pull request:

- Add needed plugins to swiper builder

**Ionic Version**: 4.0.0-beta.17

**Fixes**: #15857

### CODE REVIEW

**Comment by manucorporat** [comment]
Can you run `npm run build` and commit the changes as well? also make sure you run `npm i` before.

**Comment by kalicki** [comment]
Status?

**Comment by CFT-Chris** [comment]
Sorry, is this waiting for something on my end?  I rebuilt and committed a few weeks ago. I can do it again if needed.

**Comment by Nazirovich** [comment]
> #### Short description of what this resolves:
> Missing Coverflow, Cube, Fade and Flip swiper effects for `ion-slides`
> 
> #### Changes proposed in this pull request:
> * Add needed plugins to swiper builder
> 
> **Ionic Version**: 4.0.0-beta.17
> 
> **Fixes**: #15857

Fade effect still not working

**Comment by kalicki** [comment]
hey @manucorporat 

We're out of beta and it wasn't inserted, why? :(

**Comment by liamdebeasi** [comment]
@brandyscarney I noticed we already have swiper as a dependency on our `package.json`: https://github.com/ionic-team/ionic/blob/master/core/package.json#L58

Do we need this additional swiper.js file?

**Comment by kalicki** [comment]
Interesting, there seems to be a load by the package and its bundle separates into folder. It makes no sense this double load.

Remember that you have a new version:
https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#swiper-450---released-on-february-22-2019

**Comment by liamdebeasi** [comment]
Yeah that's interesting. I think it may be fine for now. What do you think @brandyscarney.

Re: the new swiper version-- I think this should be a separate PR, but worth looking into!

**Comment by liamdebeasi** [comment]
Hi there,

After some discussion with the team, we have decided to go a different route with the swiper animation plugins. Instead of adding the additional animations directly into the framework, we have decided to expose the event handlers that swiper provides. This has a few benefits:

1. Ionic users do not need to include the swiper animations in their bundle if they aren't using it.
2. Users can still incorporate the flip, fade, cube, and coverflow effects. We will provide instructions on how to do so in the Ionic Docs.
3. Users can also develop and integrate their own custom animations.

I have created a PR for this here: https://github.com/ionic-team/ionic/pull/17959 which will be merged instead of this PR. Any feedback on this PR would be greatly appreciated!

Thank you very much for your contributions here, we really appreciate it! You will be added as a co-contributor to #17959.

Thanks!

**Comment by brandyscarney** [comment]
I'm going to close this, please refer to Liam's comment above as to why. If anyone has feedback please add it on the Pull Request he linked to, thank you!

**Pull request closed without merging**
