### PR TITLE
fix(Slides) move global vars to Slides class members

### PR DESCRIPTION
**Pull request by akaztp**
#### Short description of what this resolves:
Having multiple slides on the same page (like the slides/loop e2e test) does not work. One cannot control the slides correctly and independently.

#### Changes proposed in this pull request:

- The variables declared in the outer scope of swiper-events.ts become global and there lays the problem. This PR moves them into the Slides class.

**Ionic Version**: 3.3.0

**Fixes**: #5837

### CODE REVIEW

**Comment by bragayann** [comment]
Hey @akaztp thanks a lot for the PR 🎉 

I'm adding this gif just to support this PR and show what issue this solves:
slides bug

**Comment by yannbf** [comment]
Hey @akaztp thanks a lot for the PR 🎉

I'm adding this gif just to support this PR and show what issue this solves:
slides bug

**Comment by HugoHeneault** [comment]
Any luck to get this PR merged? 👍

**Comment by akaztp** [comment]
No @HugoHeneault, no word from them. Maybe they have plans to rewrite the slides component.
Meanwhile, I've moved to the original [slider component](https://github.com/nolimits4web/Swiper) using the [ngx-swiper-wrapper](https://github.com/zefoy/ngx-swiper-wrapper) angular wrapper. Also found bugs on both... (on the wrapper it has been already solved!).

**Comment by CookieCookson** [comment]
I have a feeling with the way Stencil JS is going, the Slides implementation will be completely rewritten from scratch in their new component framework.

**Comment by aslaugsollilja** [comment]
hey ionic team, would be great to get this issue fixed, how about merging in this PR?

**Comment by tmk1991** [comment]
Any updates?

**Comment by HugoHeneault** [comment]
What happened with the original commit fixing this issue? Looks like a rebase made lots (!) of change appear here. 😲 
Anyone looking for the original commit, it's here if you wanna path your ionic: https://github.com/ionic-team/ionic/pull/11791/commits/322273fedb3f4297336def68d01411547dfd2bdf

**Comment by p4u1d34n** [comment]
Is there any advance on this? Would really like to see this in my new app :)

**Comment by CookieCookson** [comment]
Has anybody tested the Slides fixes that were introduced in 3.8.0+?

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#380-2017-10-26

I know there was some work done which helped with multiple slides instances and desktop mouseclick support.

**Comment by HugoHeneault** [comment]
I managed to get the different slides working and to control them by using `@ViewChild()`.

HTML:
```html
<ion-slides #slides1></ion-slides>
<ion-slides #slides2></ion-slides>
<ion-slides #slides3></ion-slides>
```
TypeScript:
```ts
@ViewChild('slides1') slides1: Slides;
@ViewChild('slides2') slides2: Slides;
@ViewChild('slides3') slides3: Slides;
```

Then I can do 

```ts
this.slides1.goNext();

// or 

this.slides2.goPrev();
```

**Comment by aslaugsollilja** [comment]
@HugoHeneault does it work to drag the slides? Its still broken for me..

**Comment by HugoHeneault** [comment]
@aslaugsollilja Yeah I'm able to drag each slide manually :)

**Comment by HugoHeneault** [comment]
Are you using 3.9.x?

**Comment by aslaugsollilja** [comment]
@HugoHeneault no I'm actually using `ionic-angular 3.4.2` but I tested out my app on a mobile device and the slides work perfectly there..

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
