### PR TITLE
fix(toggle): RTL fix for toggle

### PR DESCRIPTION
**Pull request by sijav**
#### Short description of what this resolves:
This will fix bugs of toggle component while on RTL mode

#### Changes proposed in this pull request:

- fix the transform translate3d when on RTL
- fix the toggle gesture when on RTL

**Ionic Version**: 3.x

**Fixes**: #11211

### CODE REVIEW

**Comment by AmitMY** [comment]
@sijav Looks great. Most SCSS changes will need to be reverted (only `transition` is ok to stay), as they are covered in a mixin that I hope they'll merge this week. https://github.com/driftyco/ionic/pull/11649

**Comment by sijav** [comment]
@AmitMY Oh perfect!

**Comment by AmitMY** [comment]
Ok so preparing you in advance: remove all of the scss changes, and this is 2nd priority in my list (after transform mixin)

**Comment by sijav** [comment]
@AmitMY Ok no problem I'll wait for a mixin on this

**Comment by AmitMY** [comment]
@sijav No need to wait, just remove all of the scss changes, so it can get merged immediately after transform

**Pull request merged**
