### PR TITLE
fix(card): update background to use the same as item

### LINKED ISSUE #19140: bug: card wrong background when switching between pages
# Bug Report

**Ionic version:**

[x] **4.7.4**
[x] **4.9.0**

**Current behavior:**
When i first open the app the card has the correct background color and the svg image is visible.
When i go to the list page and go back to the home page, the card has wrong background and the svg is not displayed. (check out the video)
After going back to the home page, if open and close the menu 3 times the card and the svg are displayed correctly.

https://www.youtube.com/watch?v=Z_qQeipYGw4

Edit: I also tried the conference starter and this is a video with the problem
https://www.youtube.com/watch?v=Ek4U888kKR4
The problem appears in the speakers tab where we have cards.
Also going back to the schedule tab, the fab button has bad background as well.

**Expected behavior:**
Background should not be affected when moving between pages.

**Steps to reproduce:**
Just using the sidemenu starter template with no changes at all.
Tried that with capacitor and cordova, and the i got the same problem.
`ionic start myApp sidemenu --capacitor`
`ionic build`
`ionic capacitor add android`
`ionic capacitor copy android`
`ionic capacitor open android`
Run the application from android studio
**Related code:**
The sidemenu starter template with no changes at all

```
insert short code snippets here
```

**Other information:**

Physical android phone : `huawei y5 2017 mya-l22`
Android version : `6.0`

I want to mention that i tried running the app on another device like mine and the problem exists so this is not related to my device only.
But i tried running the same app on two other samsung devices, infinix device (android 8.0), lenovo (android 5.0.2) and i didn't get this problem.
This appeared only on two huawei devices of the same model.

**Ionic info:**

```
Ionic:
  Ionic CLI                     : 5.2.5 (C:\Users\Melek\AppData\Roaming\npm\node_modules\ionic)
  Ionic Framework               : @ionic/angular 4.7.4
  @angular-devkit/build-angular : 0.801.3
  @angular-devkit/schematics    : 8.1.3
  @angular/cli                  : 8.1.3
  @ionic/angular-toolkit        : 2.0.0
Capacitor:
  Capacitor CLI   : 1.1.1
  @capacitor/core : 1.1.1
Utility:
  cordova-res : not installed
  native-run  : 0.2.8
System:
  NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
  npm    : 6.10.3
  OS     : Windows 10
```

### PR DESCRIPTION
**Pull request by brandyscarney**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Card backgrounds are transparent which causes issues

## What is the new behavior?

- uses item background but falls back to the background of the content
- this updates it so that the background will not be transparent but white

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by shadoWalker89** [comment]
Hi, thanks for the PR, is there a way i can check this right now before getting merged and released so i can tell you if it fixes the problem ?
Thanks.

**Comment by brandyscarney** [comment]
@shadoWalker89 Sure! Here is a dev build, but this is based off of our `5.0.0-beta.0` release: `5.0.0-dev.201910161728.77878e2`

See the changelog for what is in 5.0 so far: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Comment by shadoWalker89** [comment]
So this fix will not be included in the ionic 4 ?
Also how can i install the 5 beta version ? I have no clue how to do that.

**Comment by blinkuz** [comment]
> @shadoWalker89 Sure! Here is a dev build, but this is based off of our `5.0.0-beta.0` release: `5.0.0-dev.201910161728.77878e2`
> 
> See the changelog for what is in 5.0 so far: https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

This change will not be reflected in version 4.x?

**Comment by brandyscarney** [comment]
I think there's some confusion here. This PR is only to update the card background to use the following as the default:

```
var(--ion-item-background, var(--ion-background-color, #fff)
```

Prior to this it didn't fallback to the background color of the app. However, it is currently possibly to set it to do this by setting it on the `ion-card`:

```
ion-card {
  --background: var(--ion-item-background, var(--ion-background-color, #fff);
}
```

Whether or not it fixes #19140 was just a possibility but this PR will not be intended to fix that issue, only the issue of it not falling back to the background color. This will go into 5.x as this is not critical (it has a workaround).

**Comment by shadoWalker89** [comment]
@brandyscarney Thank your for your answer and explanation in details. But please could you check out the image problem  that i mentioned in my last answer ? Thanks

**Pull request merged**
