### PR TITLE
fix(input): fix display of ion-input in narrow ion-item in Firefox

### PR DESCRIPTION
**Pull request by pwespi**
#### Short description of what this resolves:
fix display of ion-input in narrow ion-item in Firefox

**Ionic Version**: 4

**Fixes**: https://github.com/ionic-team/ionic/issues/16977

### CODE REVIEW

**Comment by manucorporat** [comment]
cc @brandyscarney

**Comment by pwespi** [comment]
I just tested with the latest `@ionic/core@dev` and the issue is still there.
This PR should still work.

**Comment by brandyscarney** [comment]
@pwespi Thanks for the PR! Could you add a code example to one of the e2e tests? Maybe this one: https://github.com/ionic-team/ionic/blob/master/core/src/components/input/test/basic/index.html

That will make it easy for us to test it out and make sure it doesn't have a regression in the future. 🙂

**Comment by brandyscarney** [comment]
Also, here are some docs on previewing changes if you need them: https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#preview-changes

**Comment by brandyscarney** [comment]
@pwespi Thanks for adding the code example and for the fix! Once the build looks good I can merge this. 🙂

**Pull request merged**
