### PR TITLE
 docs(breaking): Adding a ViewChild entry

### PR DESCRIPTION
**Pull request by Youtch**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [V ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ V] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [V ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

When declaring a ion-slides...

**HTML**
```
<ion-slides #slider pager>
```
**TS**
```
@ViewChild('slider') slider:Slides;

```
 I receive an Angular error : 

> Expected 2 arguments, but got 1.
> [ng] 23    @ViewChild(slider) slider: slider:Slides;

Tested on Ionic 4.11.5. , with Angular 8 ONLY : according to the Angular.io API :
- explaining that change needed : https://v8.angular.io/api/core/ViewChild#description ; 
- explaining that no more needed : https://v9.angular.io/api/core/ViewChild#description

Issue Number: N/A

## What is the new behavior?

- Any more error message

## Does this introduce a breaking change?

- [V ] Yes
- [ ] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR! What issue does this fix? At first glance, this looks more like an Angular-specific breaking change than an Ionic one.

**Comment by Youtch** [comment]
It's true, but does it deserve a PR for the Breaking Change Documentation
beetween v3 and v4 (not v5 because it's Angular >8) ?



[image: photo]
François Gardien
Développeur | Chef de projet at  FG Solutions
A  64 rue du Breuil, 17300 Rochefort
M  06.80.18.26.43  <06.80.18.26.43>
<http://www.linkedin.com/in/fran%C3%A7ois-gardien-15496160/>
<http://github.com/Youtch>

Notre environnement est fragile, merci de n’imprimer cet email qu’en cas de
nécessité.
Create your own WiseStamp email signature
<https://www.wisestamp.com/signature-in-email/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=5021717640249344>

Le lun. 29 juin 2020 à 18:10, Liam DeBeasi <notifications@github.com> a
écrit :

**Comment by liamdebeasi** [comment]
Hmm what would be the benefit of noting this in the Ionic Framework v3-->v4 breaking changes document? v3 never supported Angular 9, so users would not have run into this issue.

**Comment by Youtch** [comment]
> Hmm what would be the benefit of noting this in the Ionic Framework v3-->v4 breaking changes document? v3 never supported Angular 9, so users would not have run into this issue.

Not exactly : This PR concerns Ionic 4 with Angular 8 (coming from Ionic 3 with Angular<8)

**Comment by liamdebeasi** [comment]
Ah ok I see, thanks for the clarification. The purpose of the breaking changes document is to note breaking changes to the Ionic Framework APIs. While this particular change may be required when migrating from Angular <8 to Angular 8, it is not a change to an Ionic Framework API. I spoke with the team, and we feel it may be confusing to note Angular breaking changes here. As a result, we have decided not to merge this PR. Thank you!

**Comment by Youtch** [comment]
Thank you for your consideration.

**Pull request closed without merging**
