### PR TITLE
feat(alert): add search bar for radio/checkbox alerts (#7873)

### PR DESCRIPTION
**Pull request by zakton5**
#### Short description of what this resolves:
A select can have many options, sometimes more than 100. It is tedious for any user to scroll through the entire list, especially if they already know what they are looking for. This PR adds an optional search bar to radio/checkbox alerts that filters down the visible options.

#### Changes proposed in this pull request:
- Add `enableSearch` property  to `AlertOptions` interface.
- Add `ion-searchbar` to alert template
- Search bar will filter the options based on the `label` property on the `AlertInputOptions` interface

**Ionic Version**: 3.x

**Fixes**: #7873 (This issue is already closed, but should not be)

### CODE REVIEW

**Comment by epetre** [comment]
Nice!

**Comment by chukwu** [comment]
I agree. I have a radio alert box of timezones. Its pretty difficult finding a timezone without a searchbar.

**Comment by zakton5** [comment]
Please don't forget this :)

**Comment by zakton5** [comment]
I've updated this branch to the latest master, so no conflicts are present at this time.

**Comment by erickbrenesLT** [comment]
This would be life saver!

**Comment by okonon** [comment]
@brandyscarney could you please take look at this?

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
