### PR TITLE
feat(alert): add search option in alert fields

### PR DESCRIPTION
**Pull request by dgaleazzo**
Hi, we implemented this feature in @gnucoop, hoping to being helpful! 

alert_search

### CODE REVIEW

**Comment by jgw96** [comment]
Hello @dgaleazzo , would you be able to fix the merge conflicts on this issue please? Thanks!

**Comment by dgaleazzo** [comment]
Hi @jgw96 

I have been fixed it.

`gulp e2e.watch`

and enjoy it at http://localhost:8000/dist/e2e/alert/basic/ 

(our senior dev @trik has been still waiting for ionic tshirt from angular-europe in Paris :rofl: )

**Comment by CarlosAyala** [comment]
Great !, I had to write a modal to implement this same function. When is will be merged?

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
