### PR TITLE
feat(toast): add support for `closeButtonIcon`

### LINKED ISSUE #16237: [v4] feature: close button icon for toasts
# Feature Request

**Ionic Info**

```
"@ionic/core": "4.0.0-beta.15"
```

**Describe the Feature Request**

Add an option `closeButtonIcon: string` to [`ToastOptions`](https://github.com/ionic-team/ionic/blob/master/core/src/components/toast/toast-interface.ts) that renders an icon instead of `closeButtonText`, or next to the `closeButtonText`.

**Describe Preferred Solution**

I mainly want to modify this part of the `ion-toast` template

https://github.com/ionic-team/ionic/blob/fda48a0e52556ca624e9641adbe851ebbd7ea92d/core/src/components/toast/toast.tsx#L206-L210

to something like this:

```tsx
<ion-button>
  {this.closeButtonIcon && (
    <ion-icon name={this.closeButtonIcon} slot={this.closeButtonText ? 'end' : 'icon-only'} />
  )}
  {this.closeButtonText || (this.closeButtonIcon ? '' : 'Close')}
</ion-button>
```

**Describe Alternatives**

None?

**Additional Context**

I'll make a PR for this, just don't have the time right now, and wanted to have a reminder for myself...

### PR DESCRIPTION
**Pull request by simonhaenisch**
#### Short description of what this resolves:

Adds the possibility to add an icon to the close button (either with or without a text).

Closes #16237.

#### Changes proposed in this pull request:

- add a `closeButtonIcon` prop to toasts

| Android | iOS |
|-|-|
|   |  |

**Ionic Version**: `4.0.0-beta.16` ?

---

I added demos to `test/basic/index.html` and `test/preview/index.html`, should I add them to `test/standalone/index.html` as well? Also, should I add new test cases to the e2e tests for that? Seems like only basic functionality of the toast, i. e., show and dismiss, is tested (maybe on purpose?).

### CODE REVIEW

**Comment by paulstelzer** [comment]
Could you resolve the conflicts with the branch?

**Comment by simonhaenisch** [comment]
@paulstelzer just merged... could you please explain why the build failed? Does that mean I have to update the API docs somewhere or something?

**Comment by paulstelzer** [comment]
You have to push the api.txt, too

**Comment by simonhaenisch** [comment]
@paulstelzer ok, I used the Github interface to resolve the conflicts... that's why I missed that. Should be ok now?

**Comment by paulstelzer** [comment]
Thanks! I try to concince @manucorporat and @brandyscarney because the icon is not something that is in MD Design - but it's optional, so I hope it's get green light ;)

**Comment by brandyscarney** [comment]
Thanks for the PR! I think if this were to be implemented the API should match how action sheet and other overlays work, for example:

```
buttons: [{
  text: 'Close',
  role: 'close',
  icon: 'trash',
  show: false // true by default
  handler: () => {
    console.log('Close clicked');
  }
}, {
```

Thoughts?

**Comment by simonhaenisch** [comment]
@brandyscarney this kind of implies that it's possible to have multiple buttons, right? Other than that I like the idea.

**Comment by brandyscarney** [comment]
> Should there also be a color option for the button? The spec says that the button color shouldn't be the same as the text button.

Hmmm yeah I would think so. But we may run into problems with passing `color` to the button since toast uses shadow (we have in the past).

I think it could go hand in hand with this issue: https://github.com/ionic-team/ionic/issues/16791#issuecomment-448329375

**Comment by simonhaenisch** [comment]
Closing in favor of #17147.

**Pull request closed without merging**
