### PR TITLE
perf(scss): optimize multi dir

### PR DESCRIPTION
**Pull request by AmitMY**
#### Short description of what this resolves:
Bundle size reduction

|     | css | min.css |
|-----|-------|----------|
| old | 602kb | 481kb    |
| new | 549kb | 439kb    |

#### Changes proposed in this pull request:

-` [dir=rtl] selector,  [dir=ltr] selector` change to `[dir] selector` as both have the same specificity

Snapshot: [ltr vs multi](http://ionic-snapshot-go.appspot.com/ionic2/snapshots/une/prz/chrome_400x800)

image

**Ionic Version**: 3.x

### CODE REVIEW

**Comment by brandyscarney** [comment]
Would this work with `[dir=auto]`? I think we've discussed this before but I don't recall.

**Comment by AmitMY** [comment]
Yes it would, it would actually be better for auto than current behavior 

However, as we discussed, auto is not supported, and that is fine because there is no use case for it

**Comment by brandyscarney** [comment]
Okay, I am fine with this change but we are currently switching the branches around so this PR may break.

**Comment by AmitMY** [comment]
wow it broke bad...
Feel free to just make the change manually (in `multi-dir` mixin change the 2 dirs to just `[dir]`)

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
