### PR TITLE
fix(angular): Synchronize css classes on form control validity status change and dirty/touched state change

### LINKED ISSUE #17414: @Ionic/Angular 4.0.0 Angular forms validation status class updates not working (ng-*** != ion-***)
# Bug Report

**Ionic version:**

4.0.0

**Current behavior:**
Using the Angular Reactive Forms API, when `markAsTouched()` function is called over a FormControl, `ng-touched` class is applied to the `ion-item` element but the `ion-touched` class is not applied. 

This problem occurs with each of the Angular Forms  `markAs***` functions:
- markAsTouched
- markAsUntouched
- markAsDirty
- markAsPristine
- markAsPending

_(Didn't take the time to test the `reset` function, but I suspect that the result will be the same.)_

**Expected behavior:**
Whenever an Angular FormControl status changes `ng-XXX` classes applied to the DOM element are updated. 
`ion-XXX` classes should work the same way. On every FormControl status change, `ion-XXX` classes should also be updated.

**Steps to reproduce:**

1. Change the status of a FormControl using the Angular Forms `markAsXXX` functions.
2. Inspect the DOM and check the `ng-XXX` and `ion-XXX` classes applied to the corresponding ion-item.
3. ng-XXX classes are applied, `ion-XXX` classes don't

**Related code:**

```

```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (D:\Users\****\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : not installed
```

### LINKED ISSUE #18426: bug: ion-item => ion-invalid style
# Bug Report

**Ionic version:**
4.4.2

**Current behavior:**
Using form with formControlName on ion-input, wrapped by ion-item, and setting error for a kind of formControl sets error on ion-input, but ion-item styles are not getting updated until we focuse/unfocuse(blur) an ion-input.

**Expected behavior:**
Styles of ion-item are updated on AbstractControl.setErrors() without any additional actions.

**Ionic info:**
 ionic (Ionic CLI)             : 4.12.0
 Ionic Framework               : @ionic/angular 4.4.2
 @angular-devkit/build-angular : 0.12.3
 @angular-devkit/schematics    : 7.1.4
 @angular/cli                  : 7.1.4
 @ionic/angular-toolkit        : 1.2.2

### LINKED ISSUE #20650: bug: Angular Reactive Form markAs** not updating Ion-Element
# Bug Report
When calling a markAs (e.g. markAsTouched) on an angular reactive form control the ion class does not update: (e.g. ng-pristine ng-invalid md in-item hydrated ion-untouched ion-pristine ion-invalid ng-touched)
(you see that angular puts ng-touched, but ionic still thinks it is ion-untouched...)

Therefore validation is not showing...

**Ionic version:**

[x] **5.x**
latest Ionic 5 Version

**Current behavior:**

The Ion-Input or Ion-Select ignore the angular validation state/classes therefore validation is not working as expected.

**Expected behavior:**

Ion Elements should align and work like the angular team designed the form validation states.

**Steps to reproduce:**

Just create a simple angular reactive form with one ion-input and call markAsTouched on that angular control.

**Related code:**
Html:
`<ion-item>
<ion-label>No Validation here !</ion-label>
    <ion-input [formControl]="inputControl"></ion-input>
  </ion-item>`

Typescript:
`inputControl: AbstractControl = new FormControl('', Validators.required);
  
  constructor(private activatedRoute: ActivatedRoute) {
    setTimeout(() => {
      this.inputControl.markAsTouched();
      this.inputControl.markAsDirty();
    }, 1000);

  }`

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

### PR DESCRIPTION
**Pull request by MarkChrisLevy**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures
Lint reports Injector.get deprecation, but it is perfectly valid when type is provided as first argument. 

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

When form control status change (e.g. from valid to invalid) Ionic validation css classes (e.g. ion-valid) do not change, which leads to invalid styling of the component.

Issue Number: fixes #17414, fixes #18426, fixes #20650

## What is the new behavior?

- When control status changed (e.g. from valid to invalid) Ionic css classes matches angular form status.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Thanks for the PR! Do you think this will fix https://github.com/ionic-team/ionic/issues/20650 as well?

**Comment by MarkChrisLevy** [comment]
Yes, markAsTouched or markAsDirty cause firing of status change event for the control, so yes, that will fix #20650 issue as well.

**Comment by MarkChrisLevy** [comment]
@liamdebeasi Ups, I was wrong. Form control status is only related to validity, but I will change PR to support state changes as well.

**Comment by liamdebeasi** [comment]
There's a feature request to do this in Angular: https://github.com/angular/angular/issues/10887. However, it's been open for 4 years, so I do not know when/if it will be implemented.

I spoke with the team, and our current plan is just to patch the form methods for now.

I am planning on opening a separate PR for this, but if we decided to merge it we will be sure to list you as a co-author 😊 .

**Comment by MarkChrisLevy** [comment]
@liamdebeasi I just verified that using angular's change detection + host property binding I can synchronize state. I will commit proper changes in a few minutes.

**Comment by MarkChrisLevy** [comment]
@liamdebeasi Just made commit. As wrote before - not as elegant as it should be but.. works :-) 

For those concerning about the performance: yes, _syncControlState will be called continuously, but if state didn't change nothing is to be done, so the cost of running a method is very little and doesn't impact app performance at all. _syncControlState always return null for not setting attribute (ion-ng-state-sync) on which we have the binding.

**Comment by liamdebeasi** [comment]
What do you mean by "may be called continuously"?

**Comment by MarkChrisLevy** [comment]
Because of how angular change detection works... It can be called as often as change detection occurs, which in case of dev mode means almost continuously.

**Comment by MarkChrisLevy** [comment]
@liamdebeasi I made small change in binding expression, which should call _syncControlState only when really needed. I also added tslint:disable-line comment for deprecation of Injector.get, which is not deprecated.

**Comment by liamdebeasi** [comment]
Thanks for the update! I think we are going to move forward with https://github.com/ionic-team/ionic/pull/21429/files instead. It has support for `markAsPending` as well and only runs at most once (whenever you call the method directly) as it is not dependent on change detection.

I made a dev build if you are interested in testing it out in your application:

`npm i @ionic/angular@5.2.0-dev.202006031626.137c49d`

**Comment by MarkChrisLevy** [comment]
Ok, should I cleanup my PR and remove commits related to markAs*?

**Comment by liamdebeasi** [comment]
You can leave it as is for now. When we merge https://github.com/ionic-team/ionic/pull/21429, we will list you as a co-author and close this PR.

**Comment by MarkChrisLevy** [comment]
But #21429 doesn't fix syncing validity status.

**Comment by liamdebeasi** [comment]
Hmm I can only reproduce the `markAs*` methods not causing the classes to sync. Validity state is working fine for me.

What methods are you using to set the validity state?

**Comment by liamdebeasi** [comment]
Ah right I see what you mean. Ok I updated my PR to use the `statusChange` subscription as well: https://github.com/ionic-team/ionic/pull/21429.

**Pull request closed without merging**
