### PR TITLE
fix(datetime): works with zero-boundary condition for max hour, minute, second.

### PR DESCRIPTION
**Pull request by flivni**
#### Short description of what this resolves:
Setting a max time at the hour boundary, e.g. 13:00 allows the user to choose any minute during the 13th hour, e.g. 13:05.

`<ion-datetime displayFormat="HH:mm" min="11:00" max="13:00"></ion-datetime>`

**Ionic Version**: 2.2

### CODE REVIEW

**Comment by flivni** [comment]
@manucorporat fyi, this one as well. Thanks.

**Comment by kensodemann** [comment]
It seems that something like `max.hour = max.hour || (max.hour === 0 ? 0 : 23)` would be safer than this `if(max.hour == null) { max.hour = 23 }`

What you have would leave `max.hour` as `undefined` if it started `undefined` where-as the code before you change would have used 23.

**Comment by flivni** [comment]
@kensodemann - Thanks for the thoughts. 

`max.hour` is never `undefined`.  

I don't know the coding standards of this project well enough to know whether your suggestion is a good one.

**Comment by kensodemann** [comment]
My only argument would be defensive coding. If something somewhere in the code was to set `max.hour` to `undefined` (or were something somewhere in the code to change to set it to undefined), then the code you have would change behavior by leaving it set to `undefined` whereas the original code would have defaulted it to 23.

I believe the only behavior you are actually trying to change is what happens when `max.hour` is set to 0.

**Comment by Ionitron** [comment]
Hello and thank you for contributing to Ionic! We have been working on porting all of the Ionic components to web components and have recently updated `master` to reflect this. This significant change has caused this pull request to break. While we really appreciate the time and effort you put into creating this, we are not able to merge it because of the newly introduced conflicts. We are extremely sorry about this. We will not be merging any more features in to v3. If this is a feature and you have the time, please resubmit this PR against the `master` branch. If this is a critical security issue in v3, we would greatly appreciate it if you would resubmit the PR against the new `v3` branch. Thanks so much for your time!

**Pull request closed without merging**
